// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_cost.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCostBudget = `-- name: GetCostBudget :one
SELECT id, tenant_id, scope_type, scope_id, period,
       limit_amount::text AS limit_amount,
       reserved_amount::text AS reserved_amount,
       spent_amount::text AS spent_amount,
       currency, status, period_start, created_at, updated_at
FROM cost_budgets
WHERE id = $1
`

type GetCostBudgetRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        string             `json:"scope_id"`
	Period         string             `json:"period"`
	LimitAmount    string             `json:"limit_amount"`
	ReservedAmount string             `json:"reserved_amount"`
	SpentAmount    string             `json:"spent_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCostBudget(ctx context.Context, id string) (GetCostBudgetRow, error) {
	row := q.db.QueryRow(ctx, getCostBudget, id)
	var i GetCostBudgetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitAmount,
		&i.ReservedAmount,
		&i.SpentAmount,
		&i.Currency,
		&i.Status,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderModelPrice = `-- name: GetProviderModelPrice :one
SELECT id, provider_id, model_id, operation_type, unit_type,
       price_per_unit::text AS price_per_unit, currency,
       effective_from, effective_to, is_active, source, notes,
       created_at, updated_at
FROM provider_model_prices
WHERE id = $1
`

type GetProviderModelPriceRow struct {
	ID            string             `json:"id"`
	ProviderID    string             `json:"provider_id"`
	ModelID       string             `json:"model_id"`
	OperationType string             `json:"operation_type"`
	UnitType      string             `json:"unit_type"`
	PricePerUnit  string             `json:"price_per_unit"`
	Currency      string             `json:"currency"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	Source        *string            `json:"source"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProviderModelPrice(ctx context.Context, id string) (GetProviderModelPriceRow, error) {
	row := q.db.QueryRow(ctx, getProviderModelPrice, id)
	var i GetProviderModelPriceRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.OperationType,
		&i.UnitType,
		&i.PricePerUnit,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec

INSERT INTO audit_events (
    id, tenant_id, event_type, actor_token_id,
    resource_type, resource_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertAuditEventParams struct {
	ID           string  `json:"id"`
	TenantID     *string `json:"tenant_id"`
	EventType    string  `json:"event_type"`
	ActorTokenID *string `json:"actor_token_id"`
	ResourceType *string `json:"resource_type"`
	ResourceID   *string `json:"resource_id"`
	Metadata     []byte  `json:"metadata"`
}

// ---------------------------------------------------------------------------
// Audit events
// ---------------------------------------------------------------------------
// InsertAuditEvent records a state-changing admin action. Written in the same
// transaction as the mutation; if it fails, the mutation fails.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.ActorTokenID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const insertCostBudget = `-- name: InsertCostBudget :one

INSERT INTO cost_budgets (
    id, tenant_id, scope_type, scope_id, period,
    limit_amount, currency, status, period_start
) VALUES (
    $1, $2, $3, $4, $5,
    $6::numeric, $7, $8, $9
)
RETURNING id, tenant_id, scope_type, scope_id, period,
          limit_amount::text AS limit_amount,
          reserved_amount::text AS reserved_amount,
          spent_amount::text AS spent_amount,
          currency, status, period_start, created_at, updated_at
`

type InsertCostBudgetParams struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	ScopeType   string             `json:"scope_type"`
	ScopeID     string             `json:"scope_id"`
	Period      string             `json:"period"`
	LimitAmount pgtype.Numeric     `json:"limit_amount"`
	Currency    string             `json:"currency"`
	Status      string             `json:"status"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

type InsertCostBudgetRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        string             `json:"scope_id"`
	Period         string             `json:"period"`
	LimitAmount    string             `json:"limit_amount"`
	ReservedAmount string             `json:"reserved_amount"`
	SpentAmount    string             `json:"spent_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------------------
// Cost budgets
// ---------------------------------------------------------------------------
// InsertCostBudget creates a budget. reserved_amount and spent_amount are
// platform-owned and start at 0; callers may not set them.
func (q *Queries) InsertCostBudget(ctx context.Context, arg InsertCostBudgetParams) (InsertCostBudgetRow, error) {
	row := q.db.QueryRow(ctx, insertCostBudget,
		arg.ID,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Period,
		arg.LimitAmount,
		arg.Currency,
		arg.Status,
		arg.PeriodStart,
	)
	var i InsertCostBudgetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitAmount,
		&i.ReservedAmount,
		&i.SpentAmount,
		&i.Currency,
		&i.Status,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderModelPrice = `-- name: InsertProviderModelPrice :one
INSERT INTO provider_model_prices (
    id, provider_id, model_id, operation_type, unit_type,
    price_per_unit, currency, effective_from, effective_to, is_active,
    source, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6::numeric, $7, now(), NULL, true,
    $8, $9
)
RETURNING id, provider_id, model_id, operation_type, unit_type,
          price_per_unit::text AS price_per_unit, currency,
          effective_from, effective_to, is_active, source, notes,
          created_at, updated_at
`

type InsertProviderModelPriceParams struct {
	ID            string         `json:"id"`
	ProviderID    string         `json:"provider_id"`
	ModelID       string         `json:"model_id"`
	OperationType string         `json:"operation_type"`
	UnitType      string         `json:"unit_type"`
	PricePerUnit  pgtype.Numeric `json:"price_per_unit"`
	Currency      string         `json:"currency"`
	Source        *string        `json:"source"`
	Notes         *string        `json:"notes"`
}

type InsertProviderModelPriceRow struct {
	ID            string             `json:"id"`
	ProviderID    string             `json:"provider_id"`
	ModelID       string             `json:"model_id"`
	OperationType string             `json:"operation_type"`
	UnitType      string             `json:"unit_type"`
	PricePerUnit  string             `json:"price_per_unit"`
	Currency      string             `json:"currency"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	Source        *string            `json:"source"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// InsertProviderModelPrice creates a new active price entry. effective_from is
// now(); effective_to is NULL (current).
func (q *Queries) InsertProviderModelPrice(ctx context.Context, arg InsertProviderModelPriceParams) (InsertProviderModelPriceRow, error) {
	row := q.db.QueryRow(ctx, insertProviderModelPrice,
		arg.ID,
		arg.ProviderID,
		arg.ModelID,
		arg.OperationType,
		arg.UnitType,
		arg.PricePerUnit,
		arg.Currency,
		arg.Source,
		arg.Notes,
	)
	var i InsertProviderModelPriceRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.OperationType,
		&i.UnitType,
		&i.PricePerUnit,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCostBudgets = `-- name: ListCostBudgets :many
SELECT id, tenant_id, scope_type, scope_id, period,
       limit_amount::text AS limit_amount,
       reserved_amount::text AS reserved_amount,
       spent_amount::text AS spent_amount,
       currency, status, period_start, created_at, updated_at
FROM cost_budgets
ORDER BY tenant_id, scope_type, scope_id, period
`

type ListCostBudgetsRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        string             `json:"scope_id"`
	Period         string             `json:"period"`
	LimitAmount    string             `json:"limit_amount"`
	ReservedAmount string             `json:"reserved_amount"`
	SpentAmount    string             `json:"spent_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCostBudgets(ctx context.Context) ([]ListCostBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listCostBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCostBudgetsRow
	for rows.Next() {
		var i ListCostBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Period,
			&i.LimitAmount,
			&i.ReservedAmount,
			&i.SpentAmount,
			&i.Currency,
			&i.Status,
			&i.PeriodStart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostReservationsAdmin = `-- name: ListCostReservationsAdmin :many

SELECT id, generation_job_id, tenant_id,
       estimated_amount::text AS estimated_amount,
       reserved_amount::text AS reserved_amount,
       actual_amount,
       currency, status, failure_reason, created_at, updated_at
FROM cost_reservations
WHERE ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5
`

type ListCostReservationsAdminParams struct {
	TenantID      *string            `json:"tenant_id"`
	Status        *string            `json:"status"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	RowLimit      int32              `json:"row_limit"`
}

type ListCostReservationsAdminRow struct {
	ID              string             `json:"id"`
	GenerationJobID string             `json:"generation_job_id"`
	TenantID        string             `json:"tenant_id"`
	EstimatedAmount string             `json:"estimated_amount"`
	ReservedAmount  string             `json:"reserved_amount"`
	ActualAmount    pgtype.Numeric     `json:"actual_amount"`
	Currency        string             `json:"currency"`
	Status          string             `json:"status"`
	FailureReason   *string            `json:"failure_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------------------
// Cost reservations (read-only admin list)
// ---------------------------------------------------------------------------
func (q *Queries) ListCostReservationsAdmin(ctx context.Context, arg ListCostReservationsAdminParams) ([]ListCostReservationsAdminRow, error) {
	rows, err := q.db.Query(ctx, listCostReservationsAdmin,
		arg.TenantID,
		arg.Status,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCostReservationsAdminRow
	for rows.Next() {
		var i ListCostReservationsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.GenerationJobID,
			&i.TenantID,
			&i.EstimatedAmount,
			&i.ReservedAmount,
			&i.ActualAmount,
			&i.Currency,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderModelPrices = `-- name: ListProviderModelPrices :many
SELECT id, provider_id, model_id, operation_type, unit_type,
       price_per_unit::text AS price_per_unit, currency,
       effective_from, effective_to, is_active, source, notes,
       created_at, updated_at
FROM provider_model_prices
ORDER BY provider_id, model_id, operation_type, effective_from DESC
`

type ListProviderModelPricesRow struct {
	ID            string             `json:"id"`
	ProviderID    string             `json:"provider_id"`
	ModelID       string             `json:"model_id"`
	OperationType string             `json:"operation_type"`
	UnitType      string             `json:"unit_type"`
	PricePerUnit  string             `json:"price_per_unit"`
	Currency      string             `json:"currency"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	Source        *string            `json:"source"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProviderModelPrices(ctx context.Context) ([]ListProviderModelPricesRow, error) {
	rows, err := q.db.Query(ctx, listProviderModelPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderModelPricesRow
	for rows.Next() {
		var i ListProviderModelPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ModelID,
			&i.OperationType,
			&i.UnitType,
			&i.PricePerUnit,
			&i.Currency,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.IsActive,
			&i.Source,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedePreviousActivePrice = `-- name: SupersedePreviousActivePrice :execrows


UPDATE provider_model_prices
SET is_active = false,
    effective_to = now(),
    updated_at = now()
WHERE provider_id = $1
  AND model_id = $2
  AND operation_type = $3
  AND is_active = true
`

type SupersedePreviousActivePriceParams struct {
	ProviderID    string `json:"provider_id"`
	ModelID       string `json:"model_id"`
	OperationType string `json:"operation_type"`
}

// Admin cost surface (docs/architecture/admin-control-surface.md §"Cost
// controls"). Phase 4B: price-book create/list/get/update, cost-budget
// create/list/update, cost-reservation list, and the audit-event write that
// every mutation shares a transaction with.
// ---------------------------------------------------------------------------
// Price book
// ---------------------------------------------------------------------------
// SupersedePreviousActivePrice ends the current active entry for a
// (provider × model × operation_type): clears is_active and stamps
// effective_to. Run in the same transaction as the new INSERT so there is
// never a window with zero (or two) active rows. :execrows reports whether an
// entry was actually superseded.
func (q *Queries) SupersedePreviousActivePrice(ctx context.Context, arg SupersedePreviousActivePriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedePreviousActivePrice, arg.ProviderID, arg.ModelID, arg.OperationType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCostBudget = `-- name: UpdateCostBudget :one
UPDATE cost_budgets
SET limit_amount = COALESCE($1, limit_amount),
    status = COALESCE($2, status),
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, scope_type, scope_id, period,
          limit_amount::text AS limit_amount,
          reserved_amount::text AS reserved_amount,
          spent_amount::text AS spent_amount,
          currency, status, period_start, created_at, updated_at
`

type UpdateCostBudgetParams struct {
	LimitAmount pgtype.Numeric `json:"limit_amount"`
	Status      *string        `json:"status"`
	ID          string         `json:"id"`
}

type UpdateCostBudgetRow struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        string             `json:"scope_id"`
	Period         string             `json:"period"`
	LimitAmount    string             `json:"limit_amount"`
	ReservedAmount string             `json:"reserved_amount"`
	SpentAmount    string             `json:"spent_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// UpdateCostBudget mutates only limit_amount and status. reserved_amount,
// spent_amount, period_start, and the scope/period identity stay platform-owned
// and fixed (period_start advances only via the lazy reservation-time reset).
func (q *Queries) UpdateCostBudget(ctx context.Context, arg UpdateCostBudgetParams) (UpdateCostBudgetRow, error) {
	row := q.db.QueryRow(ctx, updateCostBudget, arg.LimitAmount, arg.Status, arg.ID)
	var i UpdateCostBudgetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitAmount,
		&i.ReservedAmount,
		&i.SpentAmount,
		&i.Currency,
		&i.Status,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderModelPrice = `-- name: UpdateProviderModelPrice :one
UPDATE provider_model_prices
SET effective_to = CASE WHEN $1::bool THEN $2 ELSE effective_to END,
    is_active = COALESCE($3, is_active),
    notes = COALESCE($4, notes),
    updated_at = now()
WHERE id = $5
RETURNING id, provider_id, model_id, operation_type, unit_type,
          price_per_unit::text AS price_per_unit, currency,
          effective_from, effective_to, is_active, source, notes,
          created_at, updated_at
`

type UpdateProviderModelPriceParams struct {
	SetEffectiveTo bool               `json:"set_effective_to"`
	EffectiveTo    pgtype.Timestamptz `json:"effective_to"`
	IsActive       *bool              `json:"is_active"`
	Notes          *string            `json:"notes"`
	ID             string             `json:"id"`
}

type UpdateProviderModelPriceRow struct {
	ID            string             `json:"id"`
	ProviderID    string             `json:"provider_id"`
	ModelID       string             `json:"model_id"`
	OperationType string             `json:"operation_type"`
	UnitType      string             `json:"unit_type"`
	PricePerUnit  string             `json:"price_per_unit"`
	Currency      string             `json:"currency"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	Source        *string            `json:"source"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// UpdateProviderModelPrice mutates only the editable fields (effective_to,
// is_active, notes). COALESCE keeps unspecified fields unchanged.
func (q *Queries) UpdateProviderModelPrice(ctx context.Context, arg UpdateProviderModelPriceParams) (UpdateProviderModelPriceRow, error) {
	row := q.db.QueryRow(ctx, updateProviderModelPrice,
		arg.SetEffectiveTo,
		arg.EffectiveTo,
		arg.IsActive,
		arg.Notes,
		arg.ID,
	)
	var i UpdateProviderModelPriceRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.OperationType,
		&i.UnitType,
		&i.PricePerUnit,
		&i.Currency,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.IsActive,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
