// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_tokens.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveAPITokenByPrefix = `-- name: GetActiveAPITokenByPrefix :one
SELECT id, tenant_id, token_hash, scopes, environment, status, expires_at,
       rate_limit_rpm, rate_limit_rph, max_concurrent_jobs
FROM api_tokens
WHERE token_prefix = $1
`

type GetActiveAPITokenByPrefixRow struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	TokenHash         string             `json:"token_hash"`
	Scopes            []string           `json:"scopes"`
	Environment       string             `json:"environment"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RateLimitRpm      *int32             `json:"rate_limit_rpm"`
	RateLimitRph      *int32             `json:"rate_limit_rph"`
	MaxConcurrentJobs *int32             `json:"max_concurrent_jobs"`
}

func (q *Queries) GetActiveAPITokenByPrefix(ctx context.Context, tokenPrefix string) (GetActiveAPITokenByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPITokenByPrefix, tokenPrefix)
	var i GetActiveAPITokenByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.Scopes,
		&i.Environment,
		&i.Status,
		&i.ExpiresAt,
		&i.RateLimitRpm,
		&i.RateLimitRph,
		&i.MaxConcurrentJobs,
	)
	return i, err
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPITokenLastUsed, id)
	return err
}
