// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_packs.sql

package dbgen

import (
	"context"
)

const getAssetPackByID = `-- name: GetAssetPackByID :one
SELECT id, tenant_id, world_id, visual_identity_id, pack_type,
       style_profile_id, style_profile_version, visual_identity_version,
       quality_tier, status, created_by_job_id, created_by_token_id,
       created_at, updated_at
FROM asset_packs
WHERE id = $1
`

func (q *Queries) GetAssetPackByID(ctx context.Context, id string) (AssetPack, error) {
	row := q.db.QueryRow(ctx, getAssetPackByID, id)
	var i AssetPack
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.VisualIdentityID,
		&i.PackType,
		&i.StyleProfileID,
		&i.StyleProfileVersion,
		&i.VisualIdentityVersion,
		&i.QualityTier,
		&i.Status,
		&i.CreatedByJobID,
		&i.CreatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssetPack = `-- name: InsertAssetPack :one

INSERT INTO asset_packs (
    id, tenant_id, world_id, visual_identity_id, pack_type,
    style_profile_id, quality_tier, status,
    created_by_job_id, created_by_token_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, 'planned',
    $8, $9
)
RETURNING id, tenant_id, world_id, visual_identity_id, pack_type,
          style_profile_id, style_profile_version, visual_identity_version,
          quality_tier, status, created_by_job_id, created_by_token_id,
          created_at, updated_at
`

type InsertAssetPackParams struct {
	ID               string  `json:"id"`
	TenantID         string  `json:"tenant_id"`
	WorldID          string  `json:"world_id"`
	VisualIdentityID *string `json:"visual_identity_id"`
	PackType         string  `json:"pack_type"`
	StyleProfileID   string  `json:"style_profile_id"`
	QualityTier      string  `json:"quality_tier"`
	CreatedByJobID   *string `json:"created_by_job_id"`
	CreatedByTokenID *string `json:"created_by_token_id"`
}

// Pack orchestration queries (Phase 5A, ADR-008). The platform — not the
// provider adapter — owns pack fan-out: the create transaction inserts the
// asset_packs row alongside the generation_jobs row, and the worker writes
// one asset_pack_items row per generated variant.
func (q *Queries) InsertAssetPack(ctx context.Context, arg InsertAssetPackParams) (AssetPack, error) {
	row := q.db.QueryRow(ctx, insertAssetPack,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.VisualIdentityID,
		arg.PackType,
		arg.StyleProfileID,
		arg.QualityTier,
		arg.CreatedByJobID,
		arg.CreatedByTokenID,
	)
	var i AssetPack
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.VisualIdentityID,
		&i.PackType,
		&i.StyleProfileID,
		&i.StyleProfileVersion,
		&i.VisualIdentityVersion,
		&i.QualityTier,
		&i.Status,
		&i.CreatedByJobID,
		&i.CreatedByTokenID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssetPackItem = `-- name: InsertAssetPackItem :exec
INSERT INTO asset_pack_items (
    id, asset_pack_id, visual_asset_id, variant_key, sort_order
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertAssetPackItemParams struct {
	ID            string `json:"id"`
	AssetPackID   string `json:"asset_pack_id"`
	VisualAssetID string `json:"visual_asset_id"`
	VariantKey    string `json:"variant_key"`
	SortOrder     int32  `json:"sort_order"`
}

func (q *Queries) InsertAssetPackItem(ctx context.Context, arg InsertAssetPackItemParams) error {
	_, err := q.db.Exec(ctx, insertAssetPackItem,
		arg.ID,
		arg.AssetPackID,
		arg.VisualAssetID,
		arg.VariantKey,
		arg.SortOrder,
	)
	return err
}

const listAssetPackItems = `-- name: ListAssetPackItems :many
SELECT id, asset_pack_id, visual_asset_id, variant_key, sort_order, created_at
FROM asset_pack_items
WHERE asset_pack_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListAssetPackItems(ctx context.Context, assetPackID string) ([]AssetPackItem, error) {
	rows, err := q.db.Query(ctx, listAssetPackItems, assetPackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetPackItem
	for rows.Next() {
		var i AssetPackItem
		if err := rows.Scan(
			&i.ID,
			&i.AssetPackID,
			&i.VisualAssetID,
			&i.VariantKey,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGenerationJobAssetPack = `-- name: SetGenerationJobAssetPack :exec
UPDATE generation_jobs
SET asset_pack_id = $1,
    updated_at = now()
WHERE id = $2
`

type SetGenerationJobAssetPackParams struct {
	AssetPackID *string `json:"asset_pack_id"`
	ID          string  `json:"id"`
}

// SetGenerationJobAssetPack links the job to the pack it created. Run inside
// the create transaction, after both rows exist.
func (q *Queries) SetGenerationJobAssetPack(ctx context.Context, arg SetGenerationJobAssetPackParams) error {
	_, err := q.db.Exec(ctx, setGenerationJobAssetPack, arg.AssetPackID, arg.ID)
	return err
}

const updateAssetPackStatus = `-- name: UpdateAssetPackStatus :exec
UPDATE asset_packs
SET status = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateAssetPackStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAssetPackStatus(ctx context.Context, arg UpdateAssetPackStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssetPackStatus, arg.Status, arg.ID)
	return err
}
