// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cost.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const estimateOperationCost = `-- name: EstimateOperationCost :one

SELECT id AS price_id,
       unit_type,
       currency,
       (price_per_unit * $1::int)::numeric(14, 4) AS estimated_amount,
       (price_per_unit * $1::int)::numeric(14, 4)::text AS estimated_text
FROM provider_model_prices
WHERE provider_id = $2
  AND model_id = $3
  AND operation_type = $4
  AND is_active = true
ORDER BY effective_from DESC
LIMIT 1
`

type EstimateOperationCostParams struct {
	Units         int32  `json:"units"`
	ProviderID    string `json:"provider_id"`
	ModelID       string `json:"model_id"`
	OperationType string `json:"operation_type"`
}

type EstimateOperationCostRow struct {
	PriceID         string         `json:"price_id"`
	UnitType        string         `json:"unit_type"`
	Currency        string         `json:"currency"`
	EstimatedAmount pgtype.Numeric `json:"estimated_amount"`
	EstimatedText   string         `json:"estimated_text"`
}

// Cost-control pre-flight queries (docs/architecture/cost-control.md §3).
// Phase 4 implements steps 4–7 (price lookup → estimate → budget reservation).
// EstimateOperationCost loads the active price for (provider × model ×
// operation) and returns the pre-flight estimate for `units` of work. No row
// means there is no active price entry → fail closed (no_price_entry).
func (q *Queries) EstimateOperationCost(ctx context.Context, arg EstimateOperationCostParams) (EstimateOperationCostRow, error) {
	row := q.db.QueryRow(ctx, estimateOperationCost,
		arg.Units,
		arg.ProviderID,
		arg.ModelID,
		arg.OperationType,
	)
	var i EstimateOperationCostRow
	err := row.Scan(
		&i.PriceID,
		&i.UnitType,
		&i.Currency,
		&i.EstimatedAmount,
		&i.EstimatedText,
	)
	return i, err
}

const insertCostReservation = `-- name: InsertCostReservation :one
INSERT INTO cost_reservations (
    id, generation_job_id, tenant_id,
    estimated_amount, reserved_amount, currency, status, failure_reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, generation_job_id, tenant_id, estimated_amount, reserved_amount,
          actual_amount, currency, status, failure_reason, created_at, updated_at
`

type InsertCostReservationParams struct {
	ID              string         `json:"id"`
	GenerationJobID string         `json:"generation_job_id"`
	TenantID        string         `json:"tenant_id"`
	EstimatedAmount pgtype.Numeric `json:"estimated_amount"`
	ReservedAmount  pgtype.Numeric `json:"reserved_amount"`
	Currency        string         `json:"currency"`
	Status          string         `json:"status"`
	FailureReason   *string        `json:"failure_reason"`
}

// InsertCostReservation records the reservation for a job. status=reserved
// on success; status=failed with failure_reason on no_price_entry /
// budget_exceeded.
func (q *Queries) InsertCostReservation(ctx context.Context, arg InsertCostReservationParams) (CostReservation, error) {
	row := q.db.QueryRow(ctx, insertCostReservation,
		arg.ID,
		arg.GenerationJobID,
		arg.TenantID,
		arg.EstimatedAmount,
		arg.ReservedAmount,
		arg.Currency,
		arg.Status,
		arg.FailureReason,
	)
	var i CostReservation
	err := row.Scan(
		&i.ID,
		&i.GenerationJobID,
		&i.TenantID,
		&i.EstimatedAmount,
		&i.ReservedAmount,
		&i.ActualAmount,
		&i.Currency,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetsForReservation = `-- name: ListBudgetsForReservation :many
SELECT id, scope_type, scope_id, period, status,
       limit_amount, reserved_amount, spent_amount, currency
FROM cost_budgets
WHERE tenant_id = $1
  AND (
       (scope_type = 'tenant' AND scope_id = $1)
    OR (scope_type = 'token'  AND scope_id = $2)
    OR (scope_type = 'world'  AND scope_id = $3)
    OR (scope_type = 'user'   AND scope_id = $4)
  )
`

type ListBudgetsForReservationParams struct {
	TenantID string `json:"tenant_id"`
	TokenID  string `json:"token_id"`
	WorldID  string `json:"world_id"`
	UserID   string `json:"user_id"`
}

type ListBudgetsForReservationRow struct {
	ID             string         `json:"id"`
	ScopeType      string         `json:"scope_type"`
	ScopeID        string         `json:"scope_id"`
	Period         string         `json:"period"`
	Status         string         `json:"status"`
	LimitAmount    pgtype.Numeric `json:"limit_amount"`
	ReservedAmount pgtype.Numeric `json:"reserved_amount"`
	SpentAmount    pgtype.Numeric `json:"spent_amount"`
	Currency       string         `json:"currency"`
}

// ListBudgetsForReservation returns every budget that could apply to a
// request: the tenant-scope budget(s) plus any token / world / user scoped
// budgets matching the request's identifiers. The caller picks which to
// enforce (tenant always; then the narrowest applicable scope).
func (q *Queries) ListBudgetsForReservation(ctx context.Context, arg ListBudgetsForReservationParams) ([]ListBudgetsForReservationRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsForReservation,
		arg.TenantID,
		arg.TokenID,
		arg.WorldID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetsForReservationRow
	for rows.Next() {
		var i ListBudgetsForReservationRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Period,
			&i.Status,
			&i.LimitAmount,
			&i.ReservedAmount,
			&i.SpentAmount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveActiveBudget = `-- name: ReserveActiveBudget :one
UPDATE cost_budgets
SET reserved_amount = reserved_amount + $1,
    updated_at = now()
WHERE id = $2
  AND status = 'active'
  AND reserved_amount + spent_amount + $1 <= limit_amount
RETURNING id
`

type ReserveActiveBudgetParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     string         `json:"id"`
}

// ReserveActiveBudget atomically holds `amount` against an active budget.
// The conditional WHERE is the consistency point: concurrent requests that
// would collectively oversell the limit see all-but-one fail (no row
// returned → budget_exceeded).
func (q *Queries) ReserveActiveBudget(ctx context.Context, arg ReserveActiveBudgetParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveActiveBudget, arg.Amount, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const reservePausedBudget = `-- name: ReservePausedBudget :one
UPDATE cost_budgets
SET reserved_amount = reserved_amount + $1,
    updated_at = now()
WHERE id = $2
  AND status = 'paused'
RETURNING id
`

type ReservePausedBudgetParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     string         `json:"id"`
}

// ReservePausedBudget records a hold against a paused budget without
// enforcing the limit (paused = recording only; never deny).
func (q *Queries) ReservePausedBudget(ctx context.Context, arg ReservePausedBudgetParams) (string, error) {
	row := q.db.QueryRow(ctx, reservePausedBudget, arg.Amount, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resetBudgetPeriodIfElapsed = `-- name: ResetBudgetPeriodIfElapsed :execrows
UPDATE cost_budgets
SET period_start = CASE period
        WHEN 'daily'   THEN date_trunc('day',   now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
        WHEN 'monthly' THEN date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
        ELSE period_start
    END,
    spent_amount = 0,
    status = CASE WHEN status = 'exceeded' THEN 'active' ELSE status END,
    updated_at = now()
WHERE id = $1
  AND period_start < CASE period
        WHEN 'daily'   THEN date_trunc('day',   now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
        WHEN 'monthly' THEN date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
        ELSE period_start
    END
`

// ResetBudgetPeriodIfElapsed lazily rolls a budget over to its current UTC
// window (Phase 7C-1c). It runs inside the reservation transaction, before the
// limit is enforced, so a daily/monthly budget whose window has elapsed starts
// the new period clean:
//   - advance period_start to the current window start
//   - zero spent_amount
//   - clear an `exceeded` status back to `active` (paused stays paused)
//   - reserved_amount is left untouched, so a live hold opened just before the
//     reset survives until its job terminates.
//
// The WHERE period_start < <window start> guard makes the reset idempotent: two
// concurrent reservations serialize on the row lock the UPDATE takes, and only
// the first (whose period_start is still behind the window) actually resets.
// The window start is computed in UTC from now() so no clock is injected.
func (q *Queries) ResetBudgetPeriodIfElapsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, resetBudgetPeriodIfElapsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
