// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cost_lifecycle.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitBudgetHold = `-- name: CommitBudgetHold :exec
UPDATE cost_budgets
SET reserved_amount = GREATEST(reserved_amount - $1, 0),
    spent_amount = spent_amount + $1,
    updated_at = now()
WHERE id = $2
`

type CommitBudgetHoldParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     string         `json:"id"`
}

// CommitBudgetHold moves a hold's amount from reserved → spent on the budget.
// GREATEST guards against a negative reserved_amount if accounting ever drifts.
func (q *Queries) CommitBudgetHold(ctx context.Context, arg CommitBudgetHoldParams) error {
	_, err := q.db.Exec(ctx, commitBudgetHold, arg.Amount, arg.ID)
	return err
}

const commitReservationForJob = `-- name: CommitReservationForJob :one
UPDATE cost_reservations
SET status = 'committed',
    actual_amount = estimated_amount,
    updated_at = now()
WHERE generation_job_id = $1
  AND status = 'reserved'
RETURNING id, estimated_amount, reserved_amount, actual_amount, currency, tenant_id
`

type CommitReservationForJobRow struct {
	ID              string         `json:"id"`
	EstimatedAmount pgtype.Numeric `json:"estimated_amount"`
	ReservedAmount  pgtype.Numeric `json:"reserved_amount"`
	ActualAmount    pgtype.Numeric `json:"actual_amount"`
	Currency        string         `json:"currency"`
	TenantID        string         `json:"tenant_id"`
}

// CommitReservationForJob flips a reservation reserved → committed exactly
// once. No row returned means the reservation was not in `reserved` (already
// committed / released / failed) → caller treats it as a no-op and moves no
// budget. actual_amount = estimated_amount (Phase 4B: no provider-reported
// reconciliation).
func (q *Queries) CommitReservationForJob(ctx context.Context, generationJobID string) (CommitReservationForJobRow, error) {
	row := q.db.QueryRow(ctx, commitReservationForJob, generationJobID)
	var i CommitReservationForJobRow
	err := row.Scan(
		&i.ID,
		&i.EstimatedAmount,
		&i.ReservedAmount,
		&i.ActualAmount,
		&i.Currency,
		&i.TenantID,
	)
	return i, err
}

const insertBudgetHold = `-- name: InsertBudgetHold :exec
INSERT INTO cost_reservation_budget_holds (
    id, cost_reservation_id, cost_budget_id, reserved_amount, status
) VALUES (
    $1, $2, $3, $4, 'reserved'
)
`

type InsertBudgetHoldParams struct {
	ID                string         `json:"id"`
	CostReservationID string         `json:"cost_reservation_id"`
	CostBudgetID      string         `json:"cost_budget_id"`
	ReservedAmount    pgtype.Numeric `json:"reserved_amount"`
}

// InsertBudgetHold records that `reserved_amount` was credited against
// `cost_budget_id` for this reservation. Written in the same savepoint as the
// budget increment so a denied reservation rolls the hold back too. Release /
// commit reverse exactly the rows recorded here.
func (q *Queries) InsertBudgetHold(ctx context.Context, arg InsertBudgetHoldParams) error {
	_, err := q.db.Exec(ctx, insertBudgetHold,
		arg.ID,
		arg.CostReservationID,
		arg.CostBudgetID,
		arg.ReservedAmount,
	)
	return err
}

const insertFinalizerCostEvent = `-- name: InsertFinalizerCostEvent :exec
INSERT INTO generation_cost_events (
    id, tenant_id, job_id, token_id, operation,
    estimated_cost_usd, actual_cost_usd, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertFinalizerCostEventParams struct {
	ID               string         `json:"id"`
	TenantID         string         `json:"tenant_id"`
	JobID            *string        `json:"job_id"`
	TokenID          *string        `json:"token_id"`
	Operation        string         `json:"operation"`
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
	ActualCostUsd    pgtype.Numeric `json:"actual_cost_usd"`
	Status           string         `json:"status"`
}

// InsertFinalizerCostEvent writes a cost event carrying estimated/actual when
// the worker never managed to write one (best-effort fallback).
func (q *Queries) InsertFinalizerCostEvent(ctx context.Context, arg InsertFinalizerCostEventParams) error {
	_, err := q.db.Exec(ctx, insertFinalizerCostEvent,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.TokenID,
		arg.Operation,
		arg.EstimatedCostUsd,
		arg.ActualCostUsd,
		arg.Status,
	)
	return err
}

const listReservedBudgetHolds = `-- name: ListReservedBudgetHolds :many
SELECT id, cost_budget_id, reserved_amount
FROM cost_reservation_budget_holds
WHERE cost_reservation_id = $1
  AND status = 'reserved'
`

type ListReservedBudgetHoldsRow struct {
	ID             string         `json:"id"`
	CostBudgetID   string         `json:"cost_budget_id"`
	ReservedAmount pgtype.Numeric `json:"reserved_amount"`
}

// ListReservedBudgetHolds returns the still-reserved holds for a reservation.
// Processed once inside the guarded transition; marking each hold committed /
// released afterwards is belt-and-suspenders against a partial retry.
func (q *Queries) ListReservedBudgetHolds(ctx context.Context, costReservationID string) ([]ListReservedBudgetHoldsRow, error) {
	rows, err := q.db.Query(ctx, listReservedBudgetHolds, costReservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservedBudgetHoldsRow
	for rows.Next() {
		var i ListReservedBudgetHoldsRow
		if err := rows.Scan(&i.ID, &i.CostBudgetID, &i.ReservedAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBudgetHoldStatus = `-- name: MarkBudgetHoldStatus :exec
UPDATE cost_reservation_budget_holds
SET status = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'reserved'
`

type MarkBudgetHoldStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

// MarkBudgetHoldStatus records the hold's terminal state. The WHERE guard on
// status='reserved' makes a re-run a no-op.
func (q *Queries) MarkBudgetHoldStatus(ctx context.Context, arg MarkBudgetHoldStatusParams) error {
	_, err := q.db.Exec(ctx, markBudgetHoldStatus, arg.Status, arg.ID)
	return err
}

const markReservationBudgetExceeded = `-- name: MarkReservationBudgetExceeded :exec

UPDATE cost_reservations
SET status = 'failed',
    failure_reason = $1,
    reserved_amount = 0,
    updated_at = now()
WHERE id = $2
`

type MarkReservationBudgetExceededParams struct {
	FailureReason *string `json:"failure_reason"`
	ID            string  `json:"id"`
}

// Cost-reservation terminal lifecycle (docs/architecture/cost-control.md §3
// steps 9–10). Phase 4B: commit on job success, release on terminal failure.
// Idempotency lives in the reservation status guard: a reservation moves
// reserved → committed or reserved → released at most once, and the budget
// holds are processed only inside that single guarded transition.
// MarkReservationBudgetExceeded turns a freshly-inserted `reserved` row into a
// `failed` one when the budget hold is denied. The estimate stays for audit;
// reserved_amount is zeroed because the savepoint already rolled back every
// budget increment and hold this reservation made.
func (q *Queries) MarkReservationBudgetExceeded(ctx context.Context, arg MarkReservationBudgetExceededParams) error {
	_, err := q.db.Exec(ctx, markReservationBudgetExceeded, arg.FailureReason, arg.ID)
	return err
}

const releaseBudgetHold = `-- name: ReleaseBudgetHold :exec
UPDATE cost_budgets
SET reserved_amount = GREATEST(reserved_amount - $1, 0),
    updated_at = now()
WHERE id = $2
`

type ReleaseBudgetHoldParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     string         `json:"id"`
}

// ReleaseBudgetHold returns a hold's amount to the budget: drop reserved,
// leave spent untouched.
func (q *Queries) ReleaseBudgetHold(ctx context.Context, arg ReleaseBudgetHoldParams) error {
	_, err := q.db.Exec(ctx, releaseBudgetHold, arg.Amount, arg.ID)
	return err
}

const releaseReservationForJob = `-- name: ReleaseReservationForJob :one
UPDATE cost_reservations
SET status = 'released',
    updated_at = now()
WHERE generation_job_id = $1
  AND status = 'reserved'
RETURNING id, estimated_amount, reserved_amount, actual_amount, currency, tenant_id
`

type ReleaseReservationForJobRow struct {
	ID              string         `json:"id"`
	EstimatedAmount pgtype.Numeric `json:"estimated_amount"`
	ReservedAmount  pgtype.Numeric `json:"reserved_amount"`
	ActualAmount    pgtype.Numeric `json:"actual_amount"`
	Currency        string         `json:"currency"`
	TenantID        string         `json:"tenant_id"`
}

// ReleaseReservationForJob flips a reservation reserved → released exactly
// once. actual_amount stays NULL (job failed, nothing charged). No row
// returned → no-op.
func (q *Queries) ReleaseReservationForJob(ctx context.Context, generationJobID string) (ReleaseReservationForJobRow, error) {
	row := q.db.QueryRow(ctx, releaseReservationForJob, generationJobID)
	var i ReleaseReservationForJobRow
	err := row.Scan(
		&i.ID,
		&i.EstimatedAmount,
		&i.ReservedAmount,
		&i.ActualAmount,
		&i.Currency,
		&i.TenantID,
	)
	return i, err
}

const setGenerationJobActualCost = `-- name: SetGenerationJobActualCost :exec
UPDATE generation_jobs
SET actual_cost_usd = $1,
    updated_at = now()
WHERE id = $2
`

type SetGenerationJobActualCostParams struct {
	ActualCostUsd pgtype.Numeric `json:"actual_cost_usd"`
	ID            string         `json:"id"`
}

// SetGenerationJobActualCost records the committed actual on the job row.
func (q *Queries) SetGenerationJobActualCost(ctx context.Context, arg SetGenerationJobActualCostParams) error {
	_, err := q.db.Exec(ctx, setGenerationJobActualCost, arg.ActualCostUsd, arg.ID)
	return err
}

const updateLatestJobCostEvent = `-- name: UpdateLatestJobCostEvent :execrows
UPDATE generation_cost_events
SET estimated_cost_usd = $1,
    actual_cost_usd = $2,
    status = $3
WHERE id = (
    SELECT gce.id FROM generation_cost_events gce
    WHERE gce.job_id = $4
    ORDER BY gce.created_at DESC
    LIMIT 1
)
`

type UpdateLatestJobCostEventParams struct {
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
	ActualCostUsd    pgtype.Numeric `json:"actual_cost_usd"`
	Status           string         `json:"status"`
	JobID            *string        `json:"job_id"`
}

// UpdateLatestJobCostEvent stamps the estimated/actual cost and final status
// onto the most recent cost event for a job (the one the worker wrote for the
// terminal attempt). Returns the number of rows touched so the finalizer can
// insert one if the worker never wrote it.
func (q *Queries) UpdateLatestJobCostEvent(ctx context.Context, arg UpdateLatestJobCostEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLatestJobCostEvent,
		arg.EstimatedCostUsd,
		arg.ActualCostUsd,
		arg.Status,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
