// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generation_jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelGenerationJob = `-- name: CancelGenerationJob :one
UPDATE generation_jobs
SET status = 'cancelled',
    error_code = 'cancelled',
    error_message = $3,
    retryable = false,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type CancelGenerationJobParams struct {
	ID           string  `json:"id"`
	TenantID     string  `json:"tenant_id"`
	ErrorMessage *string `json:"error_message"`
}

// CancelGenerationJob transitions a non-terminal job to cancelled (Phase 7C-1a).
// The caller validates the source status under LockGenerationJobForUpdate first;
// this write sets the terminal cancel fields in the same transaction as the
// reservation release.
func (q *Queries) CancelGenerationJob(ctx context.Context, arg CancelGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, cancelGenerationJob, arg.ID, arg.TenantID, arg.ErrorMessage)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const countLiveGenerationJobsByToken = `-- name: CountLiveGenerationJobsByToken :one
SELECT count(*)
FROM generation_jobs
WHERE requested_by_token_id = $1::text
  AND status IN ('queued', 'running', 'preview_ready')
`

// Phase 7C-2: the hard concurrent-job cap counts a token's live generation
// jobs — those still occupying provider/queue capacity. preview_ready is
// deliberately included: a preview-ready job is NOT terminal (it may still need
// final generation), so it still consumes a concurrent slot. completed, failed,
// and cancelled are terminal and free the slot, so they are excluded. Runs
// inside the create transaction under the per-token advisory lock so concurrent
// creates for the same token serialize before counting. Backed by
// idx_generation_jobs_token_status.
func (q *Queries) CountLiveGenerationJobsByToken(ctx context.Context, tokenID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveGenerationJobsByToken, tokenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGenerationJobByID = `-- name: GetGenerationJobByID :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at,
       governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
       intent, transform_only, transform, max_megapixels, lazy
FROM generation_jobs
WHERE id = $1
  AND tenant_id = $2
`

type GetGenerationJobByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetGenerationJobByID(ctx context.Context, arg GetGenerationJobByIDParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByID, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const getGenerationJobByIDUnchecked = `-- name: GetGenerationJobByIDUnchecked :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at,
       governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
       intent, transform_only, transform, max_megapixels, lazy
FROM generation_jobs
WHERE id = $1
`

func (q *Queries) GetGenerationJobByIDUnchecked(ctx context.Context, id string) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByIDUnchecked, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const insertCompletedCacheHitJob = `-- name: InsertCompletedCacheHitJob :one
INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, requested_outputs,
    fallback_policy, cache_result, final_asset_ids,
    cost_estimate_usd, actual_cost_usd, completed_at
) VALUES (
    $1, $2, $3, $4, 'completed',
    $5, $6, $8,
    $7, 'exact_match', $9,
    0, 0, now()
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type InsertCompletedCacheHitJobParams struct {
	ID                 string   `json:"id"`
	TenantID           string   `json:"tenant_id"`
	WorldID            *string  `json:"world_id"`
	JobType            string   `json:"job_type"`
	RequestedByTokenID *string  `json:"requested_by_token_id"`
	InputPayload       []byte   `json:"input_payload"`
	FallbackPolicy     *string  `json:"fallback_policy"`
	RequestedOutputs   []string `json:"requested_outputs"`
	FinalAssetIds      []string `json:"final_asset_ids"`
}

// Phase 6A2 single-artifact exact reuse: insert a generation job that is
// already terminal (status = 'completed') because an existing ready asset
// satisfied the request via the deterministic artifact render hash. No provider
// work runs, so the job carries no cost_reservation_id, a zero estimate, and a
// zero actual cost — the request is genuinely free. cache_result is fixed to
// 'exact_match' and final_asset_ids points at the reused asset. This row is
// never enqueued and the worker never processes it, so the terminal-job
// finalizer (which would otherwise commit a reservation) is never invoked on it.
func (q *Queries) InsertCompletedCacheHitJob(ctx context.Context, arg InsertCompletedCacheHitJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertCompletedCacheHitJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.RequestedOutputs,
		arg.FinalAssetIds,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const insertCompletedPackReuseJob = `-- name: InsertCompletedPackReuseJob :one
INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, requested_outputs,
    fallback_policy, cache_result, final_asset_ids,
    cost_estimate_usd, actual_cost_usd, completed_at
) VALUES (
    $1, $2, $3, $4, 'completed',
    $5, $6, $8,
    $7, $9, $10,
    0, 0, now()
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type InsertCompletedPackReuseJobParams struct {
	ID                 string   `json:"id"`
	TenantID           string   `json:"tenant_id"`
	WorldID            *string  `json:"world_id"`
	JobType            string   `json:"job_type"`
	RequestedByTokenID *string  `json:"requested_by_token_id"`
	InputPayload       []byte   `json:"input_payload"`
	FallbackPolicy     *string  `json:"fallback_policy"`
	RequestedOutputs   []string `json:"requested_outputs"`
	CacheResult        *string  `json:"cache_result"`
	FinalAssetIds      []string `json:"final_asset_ids"`
}

// Phase 6A3 all-hits pack reuse: the pack analogue of InsertCompletedCacheHitJob.
// Every required role of the pack was satisfied by an existing ready asset, so
// the pack job is already terminal (status = 'completed') with no provider work:
// no cost_reservation_id, a zero estimate, a zero actual cost. Unlike the
// artifact cache-hit (which is always exact_match), a pack aggregates several
// per-role outcomes, so cache_result is a parameter (the weakest reuse tier
// across the roles: exact_match | compatible_match | preview_fallback).
// final_asset_ids points at the reused assets, in role order. This row is never
// enqueued and the worker never processes it.
func (q *Queries) InsertCompletedPackReuseJob(ctx context.Context, arg InsertCompletedPackReuseJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertCompletedPackReuseJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.RequestedOutputs,
		arg.CacheResult,
		arg.FinalAssetIds,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const insertGenerationJob = `-- name: InsertGenerationJob :one

INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, fallback_policy, cache_result
) VALUES (
    $1, $2, $3, $4, 'queued',
    $5, $6, $7, $8
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type InsertGenerationJobParams struct {
	ID                 string  `json:"id"`
	TenantID           string  `json:"tenant_id"`
	WorldID            *string `json:"world_id"`
	JobType            string  `json:"job_type"`
	RequestedByTokenID *string `json:"requested_by_token_id"`
	InputPayload       []byte  `json:"input_payload"`
	FallbackPolicy     *string `json:"fallback_policy"`
	CacheResult        *string `json:"cache_result"`
}

// CONVENTION: queries here list generation_jobs columns EXPLICITLY (not SELECT *).
// When a migration adds a column, append it to the matching RETURNING/SELECT
// lists below, or sqlc emits a per-query *Row type and the build breaks.
func (q *Queries) InsertGenerationJob(ctx context.Context, arg InsertGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertGenerationJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.CacheResult,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const lockGenerationJobForUpdate = `-- name: LockGenerationJobForUpdate :one
SELECT status
FROM generation_jobs
WHERE id = $1
  AND tenant_id = $2
FOR UPDATE
`

type LockGenerationJobForUpdateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

// LockGenerationJobForUpdate row-locks a job and returns its current status.
// It is the serialization point that makes in-flight cancel safe (Phase 7C-1):
// admin cancel and the worker's guarded asset-persist BOTH take this lock on
// the same row, so whichever commits first wins and the loser observes the
// committed status. ErrNoRows ⇒ missing or cross-tenant job (→ 404).
func (q *Queries) LockGenerationJobForUpdate(ctx context.Context, arg LockGenerationJobForUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, lockGenerationJobForUpdate, arg.ID, arg.TenantID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const lockGenerationJobRowForUpdate = `-- name: LockGenerationJobRowForUpdate :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at,
       governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
       intent, transform_only, transform, max_megapixels, lazy
FROM generation_jobs
WHERE id = $1
  AND tenant_id = $2
FOR UPDATE
`

type LockGenerationJobRowForUpdateParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

// LockGenerationJobRowForUpdate row-locks a job and returns the full row so the
// retry path can read the persisted resolved route + payload under the same
// lock it validates and reopens the job with.
func (q *Queries) LockGenerationJobRowForUpdate(ctx context.Context, arg LockGenerationJobRowForUpdateParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, lockGenerationJobRowForUpdate, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const markGenerationJobCompleted = `-- name: MarkGenerationJobCompleted :one
UPDATE generation_jobs
SET status = 'completed',
    final_asset_ids = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type MarkGenerationJobCompletedParams struct {
	ID            string   `json:"id"`
	TenantID      string   `json:"tenant_id"`
	FinalAssetIds []string `json:"final_asset_ids"`
}

func (q *Queries) MarkGenerationJobCompleted(ctx context.Context, arg MarkGenerationJobCompletedParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobCompleted, arg.ID, arg.TenantID, arg.FinalAssetIds)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const markGenerationJobFailed = `-- name: MarkGenerationJobFailed :one
UPDATE generation_jobs
SET status = 'failed',
    error_code = $3,
    error_message = $4,
    retryable = $5,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type MarkGenerationJobFailedParams struct {
	ID           string  `json:"id"`
	TenantID     string  `json:"tenant_id"`
	ErrorCode    *string `json:"error_code"`
	ErrorMessage *string `json:"error_message"`
	Retryable    *bool   `json:"retryable"`
}

func (q *Queries) MarkGenerationJobFailed(ctx context.Context, arg MarkGenerationJobFailedParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobFailed,
		arg.ID,
		arg.TenantID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Retryable,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const markGenerationJobPreviewReady = `-- name: MarkGenerationJobPreviewReady :one
UPDATE generation_jobs
SET status = 'preview_ready',
    preview_asset_ids = $3,
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type MarkGenerationJobPreviewReadyParams struct {
	ID              string   `json:"id"`
	TenantID        string   `json:"tenant_id"`
	PreviewAssetIds []string `json:"preview_asset_ids"`
}

// Phase 7B two-phase generation: the preview tier landed. Flip the job to
// preview_ready and record preview_asset_ids. This is committed BEFORE final
// generation begins (a separate transaction from final persistence) so the
// preview state is externally observable through the job read and the
// job-assets read before the final asset exists. final_asset_ids stays empty
// until MarkGenerationJobCompleted runs after final success.
func (q *Queries) MarkGenerationJobPreviewReady(ctx context.Context, arg MarkGenerationJobPreviewReadyParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobPreviewReady, arg.ID, arg.TenantID, arg.PreviewAssetIds)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const markGenerationJobRunning = `-- name: MarkGenerationJobRunning :one
UPDATE generation_jobs
SET status = 'running',
    started_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type MarkGenerationJobRunningParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) MarkGenerationJobRunning(ctx context.Context, arg MarkGenerationJobRunningParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobRunning, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const retryResetGenerationJob = `-- name: RetryResetGenerationJob :one
UPDATE generation_jobs
SET status = 'queued',
    error_code = NULL,
    error_message = NULL,
    retryable = NULL,
    started_at = NULL,
    completed_at = NULL,
    final_asset_ids = '{}',
    cost_reservation_id = $1,
    cost_estimate_usd = $2,
    actual_cost_usd = NULL,
    updated_at = now()
WHERE id = $3
  AND tenant_id = $4
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at,
          governance_envelope, classification_id, visibility, content_class, authorized_by, governance_verified_at,
          intent, transform_only, transform, max_megapixels, lazy
`

type RetryResetGenerationJobParams struct {
	CostReservationID *string        `json:"cost_reservation_id"`
	CostEstimateUsd   pgtype.Numeric `json:"cost_estimate_usd"`
	ID                string         `json:"id"`
	TenantID          string         `json:"tenant_id"`
}

// RetryResetGenerationJob reopens a failed job (Phase 7C-1b). It keeps the job
// identity, payload, fallback policy, delivery mode, persisted resolved route,
// and preview_asset_ids, but clears the terminal failure fields and the run
// timestamps, links the fresh cost reservation + estimate, and clears
// final_asset_ids so a prior failed-final attempt leaves no stale final output.
// The caller validates the source status is 'failed' under
// LockGenerationJobForUpdate and reserves cost in the same transaction.
func (q *Queries) RetryResetGenerationJob(ctx context.Context, arg RetryResetGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, retryResetGenerationJob,
		arg.CostReservationID,
		arg.CostEstimateUsd,
		arg.ID,
		arg.TenantID,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.GovernanceEnvelope,
		&i.ClassificationID,
		&i.Visibility,
		&i.ContentClass,
		&i.AuthorizedBy,
		&i.GovernanceVerifiedAt,
		&i.Intent,
		&i.TransformOnly,
		&i.Transform,
		&i.MaxMegapixels,
		&i.Lazy,
	)
	return i, err
}

const setGenerationJobCost = `-- name: SetGenerationJobCost :exec
UPDATE generation_jobs
SET cost_reservation_id = $1,
    cost_estimate_usd = $2,
    updated_at = now()
WHERE id = $3
`

type SetGenerationJobCostParams struct {
	CostReservationID *string        `json:"cost_reservation_id"`
	CostEstimateUsd   pgtype.Numeric `json:"cost_estimate_usd"`
	ID                string         `json:"id"`
}

// SetGenerationJobCost links a job to its cost_reservation and records the
// pre-flight estimate. Run inside the create transaction, after the
// reservation row exists.
func (q *Queries) SetGenerationJobCost(ctx context.Context, arg SetGenerationJobCostParams) error {
	_, err := q.db.Exec(ctx, setGenerationJobCost, arg.CostReservationID, arg.CostEstimateUsd, arg.ID)
	return err
}
