// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generation_jobs.sql

package dbgen

import (
	"context"
)

const getGenerationJobByID = `-- name: GetGenerationJobByID :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at
FROM generation_jobs
WHERE id = $1
  AND tenant_id = $2
`

type GetGenerationJobByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetGenerationJobByID(ctx context.Context, arg GetGenerationJobByIDParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByID, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getGenerationJobByIDUnchecked = `-- name: GetGenerationJobByIDUnchecked :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at
FROM generation_jobs
WHERE id = $1
`

func (q *Queries) GetGenerationJobByIDUnchecked(ctx context.Context, id string) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByIDUnchecked, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertGenerationJob = `-- name: InsertGenerationJob :one
INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, fallback_policy, cache_result
) VALUES (
    $1, $2, $3, $4, 'queued',
    $5, $6, $7, $8
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type InsertGenerationJobParams struct {
	ID                 string  `json:"id"`
	TenantID           string  `json:"tenant_id"`
	WorldID            *string `json:"world_id"`
	JobType            string  `json:"job_type"`
	RequestedByTokenID *string `json:"requested_by_token_id"`
	InputPayload       []byte  `json:"input_payload"`
	FallbackPolicy     *string `json:"fallback_policy"`
	CacheResult        *string `json:"cache_result"`
}

func (q *Queries) InsertGenerationJob(ctx context.Context, arg InsertGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertGenerationJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.CacheResult,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markGenerationJobCompleted = `-- name: MarkGenerationJobCompleted :one
UPDATE generation_jobs
SET status = 'completed',
    final_asset_ids = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type MarkGenerationJobCompletedParams struct {
	ID            string   `json:"id"`
	TenantID      string   `json:"tenant_id"`
	FinalAssetIds []string `json:"final_asset_ids"`
}

func (q *Queries) MarkGenerationJobCompleted(ctx context.Context, arg MarkGenerationJobCompletedParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobCompleted, arg.ID, arg.TenantID, arg.FinalAssetIds)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markGenerationJobFailed = `-- name: MarkGenerationJobFailed :one
UPDATE generation_jobs
SET status = 'failed',
    error_code = $3,
    error_message = $4,
    retryable = $5,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type MarkGenerationJobFailedParams struct {
	ID           string  `json:"id"`
	TenantID     string  `json:"tenant_id"`
	ErrorCode    *string `json:"error_code"`
	ErrorMessage *string `json:"error_message"`
	Retryable    *bool   `json:"retryable"`
}

func (q *Queries) MarkGenerationJobFailed(ctx context.Context, arg MarkGenerationJobFailedParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobFailed,
		arg.ID,
		arg.TenantID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Retryable,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markGenerationJobRunning = `-- name: MarkGenerationJobRunning :one
UPDATE generation_jobs
SET status = 'running',
    started_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type MarkGenerationJobRunningParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) MarkGenerationJobRunning(ctx context.Context, arg MarkGenerationJobRunningParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobRunning, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
