// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generation_jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGenerationJobByID = `-- name: GetGenerationJobByID :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at
FROM generation_jobs
WHERE id = $1
  AND tenant_id = $2
`

type GetGenerationJobByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetGenerationJobByID(ctx context.Context, arg GetGenerationJobByIDParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByID, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getGenerationJobByIDUnchecked = `-- name: GetGenerationJobByIDUnchecked :one
SELECT id, tenant_id, world_id, job_type, status,
       requested_by_token_id, visual_identity_id, asset_pack_id,
       input_payload, requested_outputs, fallback_policy, cache_result,
       preview_asset_ids, final_asset_ids,
       error_code, error_message, retryable,
       cost_reservation_id, cost_estimate_usd, actual_cost_usd,
       queue_duration_ms, generation_duration_ms,
       created_at, updated_at, started_at, completed_at
FROM generation_jobs
WHERE id = $1
`

func (q *Queries) GetGenerationJobByIDUnchecked(ctx context.Context, id string) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByIDUnchecked, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertCompletedCacheHitJob = `-- name: InsertCompletedCacheHitJob :one
INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, requested_outputs,
    fallback_policy, cache_result, final_asset_ids,
    cost_estimate_usd, actual_cost_usd, completed_at
) VALUES (
    $1, $2, $3, $4, 'completed',
    $5, $6, $8,
    $7, 'exact_match', $9,
    0, 0, now()
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type InsertCompletedCacheHitJobParams struct {
	ID                 string   `json:"id"`
	TenantID           string   `json:"tenant_id"`
	WorldID            *string  `json:"world_id"`
	JobType            string   `json:"job_type"`
	RequestedByTokenID *string  `json:"requested_by_token_id"`
	InputPayload       []byte   `json:"input_payload"`
	FallbackPolicy     *string  `json:"fallback_policy"`
	RequestedOutputs   []string `json:"requested_outputs"`
	FinalAssetIds      []string `json:"final_asset_ids"`
}

// Phase 6A2 single-artifact exact reuse: insert a generation job that is
// already terminal (status = 'completed') because an existing ready asset
// satisfied the request via the deterministic artifact render hash. No provider
// work runs, so the job carries no cost_reservation_id, a zero estimate, and a
// zero actual cost — the request is genuinely free. cache_result is fixed to
// 'exact_match' and final_asset_ids points at the reused asset. This row is
// never enqueued and the worker never processes it, so the terminal-job
// finalizer (which would otherwise commit a reservation) is never invoked on it.
func (q *Queries) InsertCompletedCacheHitJob(ctx context.Context, arg InsertCompletedCacheHitJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertCompletedCacheHitJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.RequestedOutputs,
		arg.FinalAssetIds,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertCompletedPackReuseJob = `-- name: InsertCompletedPackReuseJob :one
INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, requested_outputs,
    fallback_policy, cache_result, final_asset_ids,
    cost_estimate_usd, actual_cost_usd, completed_at
) VALUES (
    $1, $2, $3, $4, 'completed',
    $5, $6, $8,
    $7, $9, $10,
    0, 0, now()
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type InsertCompletedPackReuseJobParams struct {
	ID                 string   `json:"id"`
	TenantID           string   `json:"tenant_id"`
	WorldID            *string  `json:"world_id"`
	JobType            string   `json:"job_type"`
	RequestedByTokenID *string  `json:"requested_by_token_id"`
	InputPayload       []byte   `json:"input_payload"`
	FallbackPolicy     *string  `json:"fallback_policy"`
	RequestedOutputs   []string `json:"requested_outputs"`
	CacheResult        *string  `json:"cache_result"`
	FinalAssetIds      []string `json:"final_asset_ids"`
}

// Phase 6A3 all-hits pack reuse: the pack analogue of InsertCompletedCacheHitJob.
// Every required role of the pack was satisfied by an existing ready asset, so
// the pack job is already terminal (status = 'completed') with no provider work:
// no cost_reservation_id, a zero estimate, a zero actual cost. Unlike the
// artifact cache-hit (which is always exact_match), a pack aggregates several
// per-role outcomes, so cache_result is a parameter (the weakest reuse tier
// across the roles: exact_match | compatible_match | preview_fallback).
// final_asset_ids points at the reused assets, in role order. This row is never
// enqueued and the worker never processes it.
func (q *Queries) InsertCompletedPackReuseJob(ctx context.Context, arg InsertCompletedPackReuseJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertCompletedPackReuseJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.RequestedOutputs,
		arg.CacheResult,
		arg.FinalAssetIds,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertGenerationJob = `-- name: InsertGenerationJob :one
INSERT INTO generation_jobs (
    id, tenant_id, world_id, job_type, status,
    requested_by_token_id, input_payload, fallback_policy, cache_result
) VALUES (
    $1, $2, $3, $4, 'queued',
    $5, $6, $7, $8
)
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type InsertGenerationJobParams struct {
	ID                 string  `json:"id"`
	TenantID           string  `json:"tenant_id"`
	WorldID            *string `json:"world_id"`
	JobType            string  `json:"job_type"`
	RequestedByTokenID *string `json:"requested_by_token_id"`
	InputPayload       []byte  `json:"input_payload"`
	FallbackPolicy     *string `json:"fallback_policy"`
	CacheResult        *string `json:"cache_result"`
}

func (q *Queries) InsertGenerationJob(ctx context.Context, arg InsertGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, insertGenerationJob,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.JobType,
		arg.RequestedByTokenID,
		arg.InputPayload,
		arg.FallbackPolicy,
		arg.CacheResult,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markGenerationJobCompleted = `-- name: MarkGenerationJobCompleted :one
UPDATE generation_jobs
SET status = 'completed',
    final_asset_ids = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type MarkGenerationJobCompletedParams struct {
	ID            string   `json:"id"`
	TenantID      string   `json:"tenant_id"`
	FinalAssetIds []string `json:"final_asset_ids"`
}

func (q *Queries) MarkGenerationJobCompleted(ctx context.Context, arg MarkGenerationJobCompletedParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobCompleted, arg.ID, arg.TenantID, arg.FinalAssetIds)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markGenerationJobFailed = `-- name: MarkGenerationJobFailed :one
UPDATE generation_jobs
SET status = 'failed',
    error_code = $3,
    error_message = $4,
    retryable = $5,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type MarkGenerationJobFailedParams struct {
	ID           string  `json:"id"`
	TenantID     string  `json:"tenant_id"`
	ErrorCode    *string `json:"error_code"`
	ErrorMessage *string `json:"error_message"`
	Retryable    *bool   `json:"retryable"`
}

func (q *Queries) MarkGenerationJobFailed(ctx context.Context, arg MarkGenerationJobFailedParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobFailed,
		arg.ID,
		arg.TenantID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Retryable,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markGenerationJobRunning = `-- name: MarkGenerationJobRunning :one
UPDATE generation_jobs
SET status = 'running',
    started_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, world_id, job_type, status,
          requested_by_token_id, visual_identity_id, asset_pack_id,
          input_payload, requested_outputs, fallback_policy, cache_result,
          preview_asset_ids, final_asset_ids,
          error_code, error_message, retryable,
          cost_reservation_id, cost_estimate_usd, actual_cost_usd,
          queue_duration_ms, generation_duration_ms,
          created_at, updated_at, started_at, completed_at
`

type MarkGenerationJobRunningParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) MarkGenerationJobRunning(ctx context.Context, arg MarkGenerationJobRunningParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, markGenerationJobRunning, arg.ID, arg.TenantID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.JobType,
		&i.Status,
		&i.RequestedByTokenID,
		&i.VisualIdentityID,
		&i.AssetPackID,
		&i.InputPayload,
		&i.RequestedOutputs,
		&i.FallbackPolicy,
		&i.CacheResult,
		&i.PreviewAssetIds,
		&i.FinalAssetIds,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.CostReservationID,
		&i.CostEstimateUsd,
		&i.ActualCostUsd,
		&i.QueueDurationMs,
		&i.GenerationDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setGenerationJobCost = `-- name: SetGenerationJobCost :exec
UPDATE generation_jobs
SET cost_reservation_id = $1,
    cost_estimate_usd = $2,
    updated_at = now()
WHERE id = $3
`

type SetGenerationJobCostParams struct {
	CostReservationID *string        `json:"cost_reservation_id"`
	CostEstimateUsd   pgtype.Numeric `json:"cost_estimate_usd"`
	ID                string         `json:"id"`
}

// SetGenerationJobCost links a job to its cost_reservation and records the
// pre-flight estimate. Run inside the create transaction, after the
// reservation row exists.
func (q *Queries) SetGenerationJobCost(ctx context.Context, arg SetGenerationJobCostParams) error {
	_, err := q.db.Exec(ctx, setGenerationJobCost, arg.CostReservationID, arg.CostEstimateUsd, arg.ID)
	return err
}
