// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: idempotency_keys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, token_id, key, endpoint, request_hash, generation_job_id,
       expires_at, created_at
FROM idempotency_keys
WHERE token_id = $1
  AND key = $2
`

type GetIdempotencyKeyParams struct {
	TokenID string `json:"token_id"`
	Key     string `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TokenID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.GenerationJobID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (
    id, token_id, key, endpoint, request_hash,
    generation_job_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
ON CONFLICT (token_id, key) DO NOTHING
RETURNING id, token_id, key, endpoint, request_hash, generation_job_id,
          expires_at, created_at
`

type InsertIdempotencyKeyParams struct {
	ID              string             `json:"id"`
	TokenID         string             `json:"token_id"`
	Key             string             `json:"key"`
	Endpoint        string             `json:"endpoint"`
	RequestHash     string             `json:"request_hash"`
	GenerationJobID *string            `json:"generation_job_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.ID,
		arg.TokenID,
		arg.Key,
		arg.Endpoint,
		arg.RequestHash,
		arg.GenerationJobID,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.GenerationJobID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
