// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	TokenPrefix string             `json:"token_prefix"`
	TokenHash   string             `json:"token_hash"`
	Name        string             `json:"name"`
	OwnerType   string             `json:"owner_type"`
	OwnerID     *string            `json:"owner_id"`
	Scopes      []string           `json:"scopes"`
	Environment string             `json:"environment"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AssetPack struct {
	ID                    string             `json:"id"`
	TenantID              string             `json:"tenant_id"`
	WorldID               string             `json:"world_id"`
	VisualIdentityID      *string            `json:"visual_identity_id"`
	PackType              string             `json:"pack_type"`
	StyleProfileID        string             `json:"style_profile_id"`
	StyleProfileVersion   *int32             `json:"style_profile_version"`
	VisualIdentityVersion *int32             `json:"visual_identity_version"`
	QualityTier           string             `json:"quality_tier"`
	Status                string             `json:"status"`
	CreatedByJobID        *string            `json:"created_by_job_id"`
	CreatedByTokenID      *string            `json:"created_by_token_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AssetPackItem struct {
	ID            string             `json:"id"`
	AssetPackID   string             `json:"asset_pack_id"`
	VisualAssetID string             `json:"visual_asset_id"`
	VariantKey    string             `json:"variant_key"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID           string             `json:"id"`
	TenantID     *string            `json:"tenant_id"`
	EventType    string             `json:"event_type"`
	ActorTokenID *string            `json:"actor_token_id"`
	WorldID      *string            `json:"world_id"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CostBudget struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        string             `json:"scope_id"`
	Period         string             `json:"period"`
	LimitAmount    pgtype.Numeric     `json:"limit_amount"`
	ReservedAmount pgtype.Numeric     `json:"reserved_amount"`
	SpentAmount    pgtype.Numeric     `json:"spent_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CostReservation struct {
	ID              string             `json:"id"`
	GenerationJobID string             `json:"generation_job_id"`
	TenantID        string             `json:"tenant_id"`
	EstimatedAmount pgtype.Numeric     `json:"estimated_amount"`
	ReservedAmount  pgtype.Numeric     `json:"reserved_amount"`
	ActualAmount    pgtype.Numeric     `json:"actual_amount"`
	Currency        string             `json:"currency"`
	Status          string             `json:"status"`
	FailureReason   *string            `json:"failure_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CostReservationBudgetHold struct {
	ID                string             `json:"id"`
	CostReservationID string             `json:"cost_reservation_id"`
	CostBudgetID      string             `json:"cost_budget_id"`
	ReservedAmount    pgtype.Numeric     `json:"reserved_amount"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type GenerationCostEvent struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	JobID             *string            `json:"job_id"`
	AssetID           *string            `json:"asset_id"`
	TokenID           *string            `json:"token_id"`
	ProviderID        *string            `json:"provider_id"`
	ModelID           *string            `json:"model_id"`
	ProviderAttemptID *string            `json:"provider_attempt_id"`
	Operation         string             `json:"operation"`
	EstimatedCostUsd  pgtype.Numeric     `json:"estimated_cost_usd"`
	ActualCostUsd     pgtype.Numeric     `json:"actual_cost_usd"`
	DurationMs        *int32             `json:"duration_ms"`
	Status            string             `json:"status"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type GenerationJob struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	WorldID              *string            `json:"world_id"`
	JobType              string             `json:"job_type"`
	Status               string             `json:"status"`
	RequestedByTokenID   *string            `json:"requested_by_token_id"`
	VisualIdentityID     *string            `json:"visual_identity_id"`
	AssetPackID          *string            `json:"asset_pack_id"`
	InputPayload         []byte             `json:"input_payload"`
	RequestedOutputs     []string           `json:"requested_outputs"`
	FallbackPolicy       *string            `json:"fallback_policy"`
	CacheResult          *string            `json:"cache_result"`
	PreviewAssetIds      []string           `json:"preview_asset_ids"`
	FinalAssetIds        []string           `json:"final_asset_ids"`
	ErrorCode            *string            `json:"error_code"`
	ErrorMessage         *string            `json:"error_message"`
	Retryable            *bool              `json:"retryable"`
	CostReservationID    *string            `json:"cost_reservation_id"`
	CostEstimateUsd      pgtype.Numeric     `json:"cost_estimate_usd"`
	ActualCostUsd        pgtype.Numeric     `json:"actual_cost_usd"`
	QueueDurationMs      *int32             `json:"queue_duration_ms"`
	GenerationDurationMs *int32             `json:"generation_duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
}

type IdempotencyKey struct {
	ID              string             `json:"id"`
	TokenID         string             `json:"token_id"`
	Key             string             `json:"key"`
	Endpoint        string             `json:"endpoint"`
	RequestHash     string             `json:"request_hash"`
	GenerationJobID *string            `json:"generation_job_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProviderAttempt struct {
	ID                 string             `json:"id"`
	GenerationJobID    string             `json:"generation_job_id"`
	ProviderID         string             `json:"provider_id"`
	ModelID            *string            `json:"model_id"`
	ProviderRouteID    *string            `json:"provider_route_id"`
	ProviderRequestID  *string            `json:"provider_request_id"`
	AttemptNumber      int32              `json:"attempt_number"`
	Status             string             `json:"status"`
	ErrorCode          *string            `json:"error_code"`
	ErrorMessage       *string            `json:"error_message"`
	RequestPayloadHash *string            `json:"request_payload_hash"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	LatencyMs          *int32             `json:"latency_ms"`
	EstimatedCost      pgtype.Numeric     `json:"estimated_cost"`
	ActualCost         pgtype.Numeric     `json:"actual_cost"`
	Currency           string             `json:"currency"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ProviderModel struct {
	ID                    string             `json:"id"`
	ProviderID            string             `json:"provider_id"`
	ModelName             string             `json:"model_name"`
	DisplayName           string             `json:"display_name"`
	Capabilities          []string           `json:"capabilities"`
	PreviewCapability     string             `json:"preview_capability"`
	SupportsHighRes       bool               `json:"supports_high_res"`
	MaxBatchSize          *int32             `json:"max_batch_size"`
	SupportedAspectRatios []string           `json:"supported_aspect_ratios"`
	Status                string             `json:"status"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ProviderModelPrice struct {
	ID            string             `json:"id"`
	ProviderID    string             `json:"provider_id"`
	ModelID       string             `json:"model_id"`
	OperationType string             `json:"operation_type"`
	UnitType      string             `json:"unit_type"`
	PricePerUnit  pgtype.Numeric     `json:"price_per_unit"`
	Currency      string             `json:"currency"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `json:"effective_to"`
	IsActive      bool               `json:"is_active"`
	Source        *string            `json:"source"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProviderRoute struct {
	ID                    string             `json:"id"`
	ProviderID            string             `json:"provider_id"`
	ModelID               string             `json:"model_id"`
	RouteName             *string            `json:"route_name"`
	OperationType         string             `json:"operation_type"`
	RequiredCapability    string             `json:"required_capability"`
	PreviewCapability     string             `json:"preview_capability"`
	QualityTier           string             `json:"quality_tier"`
	LatencyTier           string             `json:"latency_tier"`
	IsEnabled             bool               `json:"is_enabled"`
	Priority              int32              `json:"priority"`
	Weight                int32              `json:"weight"`
	MaxConcurrentJobs     *int32             `json:"max_concurrent_jobs"`
	AllowUnpricedProvider bool               `json:"allow_unpriced_provider"`
	DisabledReason        *string            `json:"disabled_reason"`
	DisabledByTokenID     *string            `json:"disabled_by_token_id"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type StyleProfile struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	WorldID                *string            `json:"world_id"`
	Name                   string             `json:"name"`
	StyleMode              string             `json:"style_mode"`
	StyleProfileVersion    int32              `json:"style_profile_version"`
	PositivePrompt         string             `json:"positive_prompt"`
	NegativePrompt         *string            `json:"negative_prompt"`
	Loras                  []string           `json:"loras"`
	ReferenceStyleAssetIds []string           `json:"reference_style_asset_ids"`
	DefaultQualityTier     string             `json:"default_quality_tier"`
	Status                 string             `json:"status"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type VisualAsset struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	WorldID             string             `json:"world_id"`
	VisualIdentityID    *string            `json:"visual_identity_id"`
	AssetType           string             `json:"asset_type"`
	VariantKey          string             `json:"variant_key"`
	VariantFamily       *string            `json:"variant_family"`
	Version             int32              `json:"version"`
	StateVersion        int32              `json:"state_version"`
	StyleProfileID      *string            `json:"style_profile_id"`
	StyleProfileVersion *int32             `json:"style_profile_version"`
	QualityTier         string             `json:"quality_tier"`
	Status              string             `json:"status"`
	CompatibilityTags   []string           `json:"compatibility_tags"`
	FallbackAllowed     bool               `json:"fallback_allowed"`
	FallbackRank        *int32             `json:"fallback_rank"`
	IsIdentityAnchor    bool               `json:"is_identity_anchor"`
	LowResUrl           *string            `json:"low_res_url"`
	HighResUrl          *string            `json:"high_res_url"`
	ThumbnailUrl        *string            `json:"thumbnail_url"`
	ProviderID          *string            `json:"provider_id"`
	ModelID             *string            `json:"model_id"`
	ProviderRouteID     *string            `json:"provider_route_id"`
	PromptHash          *string            `json:"prompt_hash"`
	Seed                *string            `json:"seed"`
	ReferenceAssetIds   []string           `json:"reference_asset_ids"`
	GenerationJobID     *string            `json:"generation_job_id"`
	Metadata            []byte             `json:"metadata"`
	GeneratedAt         pgtype.Timestamptz `json:"generated_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type VisualIdentity struct {
	ID                    string             `json:"id"`
	TenantID              string             `json:"tenant_id"`
	WorldID               string             `json:"world_id"`
	OwnerType             string             `json:"owner_type"`
	OwnerID               string             `json:"owner_id"`
	DisplayName           string             `json:"display_name"`
	CanonicalVisualTraits []byte             `json:"canonical_visual_traits"`
	AllowedVariation      []byte             `json:"allowed_variation"`
	ForbiddenDrift        []byte             `json:"forbidden_drift"`
	StyleProfileID        string             `json:"style_profile_id"`
	ConsistencyKey        *string            `json:"consistency_key"`
	IdentitySeed          *string            `json:"identity_seed"`
	AnchorAssetIds        []string           `json:"anchor_asset_ids"`
	ReferenceAssetIds     []string           `json:"reference_asset_ids"`
	CurrentVersion        int32              `json:"current_version"`
	CurrentStateVersion   int32              `json:"current_state_version"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type VisualIdentityVersion struct {
	VisualIdentityID        string             `json:"visual_identity_id"`
	Version                 int32              `json:"version"`
	Reason                  string             `json:"reason"`
	CanonicalTraitsSnapshot []byte             `json:"canonical_traits_snapshot"`
	AnchorAssetIds          []string           `json:"anchor_asset_ids"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}
