// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: provider_routes.sql

package dbgen

import (
	"context"
)

const listProviderRoutesForOperation = `-- name: ListProviderRoutesForOperation :many

SELECT
    r.id                  AS route_id,
    r.provider_id         AS provider_id,
    r.model_id            AS model_id,
    r.operation_type      AS operation_type,
    r.required_capability AS required_capability,
    r.preview_capability  AS preview_capability,
    r.quality_tier        AS quality_tier,
    r.latency_tier        AS latency_tier,
    r.is_enabled          AS is_enabled,
    r.priority            AS priority,
    m.status              AS model_status
FROM provider_routes r
JOIN provider_models m ON m.id = r.model_id
WHERE r.operation_type = $1
ORDER BY r.priority ASC, r.provider_id ASC, r.model_id ASC, r.id ASC
`

type ListProviderRoutesForOperationRow struct {
	RouteID            string `json:"route_id"`
	ProviderID         string `json:"provider_id"`
	ModelID            string `json:"model_id"`
	OperationType      string `json:"operation_type"`
	RequiredCapability string `json:"required_capability"`
	PreviewCapability  string `json:"preview_capability"`
	QualityTier        string `json:"quality_tier"`
	LatencyTier        string `json:"latency_tier"`
	IsEnabled          bool   `json:"is_enabled"`
	Priority           int32  `json:"priority"`
	ModelStatus        string `json:"model_status"`
}

// Provider routing substrate (Phase 7A, internal/providers/routing).
//
// ListProviderRoutesForOperation returns every route for an operation joined to
// its model's status, so the deterministic resolver can filter on active route
// + active model, match quality/latency tiers and capability, apply provider
// availability, and tie-break — all in one place it can also unit-test.
//
// Prices are deliberately NOT consulted here. Route selection is independent of
// pricing; the resolved model is then priced at cost-reservation time, where a
// missing/expired active price surfaces as no_price_entry (422). Keeping the two
// concerns separate is what lets a request fail with no_route vs no_price_entry
// for the right reason.
func (q *Queries) ListProviderRoutesForOperation(ctx context.Context, operationType string) ([]ListProviderRoutesForOperationRow, error) {
	rows, err := q.db.Query(ctx, listProviderRoutesForOperation, operationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderRoutesForOperationRow
	for rows.Next() {
		var i ListProviderRoutesForOperationRow
		if err := rows.Scan(
			&i.RouteID,
			&i.ProviderID,
			&i.ModelID,
			&i.OperationType,
			&i.RequiredCapability,
			&i.PreviewCapability,
			&i.QualityTier,
			&i.LatencyTier,
			&i.IsEnabled,
			&i.Priority,
			&i.ModelStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
