// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: provider_attempts.sql

package dbgen

import (
	"context"
)

const countProviderAttemptsForJob = `-- name: CountProviderAttemptsForJob :one
SELECT count(*)::int AS attempt_count
FROM provider_attempts
WHERE generation_job_id = $1
`

func (q *Queries) CountProviderAttemptsForJob(ctx context.Context, generationJobID string) (int32, error) {
	row := q.db.QueryRow(ctx, countProviderAttemptsForJob, generationJobID)
	var attempt_count int32
	err := row.Scan(&attempt_count)
	return attempt_count, err
}

const insertProviderAttempt = `-- name: InsertProviderAttempt :one
INSERT INTO provider_attempts (
    id, generation_job_id, provider_id, attempt_number, status
) VALUES (
    $1, $2, $3, $4, 'started'
)
RETURNING id, generation_job_id, provider_id, model_id, provider_route_id,
          provider_request_id, attempt_number, status,
          error_code, error_message, request_payload_hash,
          started_at, completed_at, latency_ms,
          estimated_cost, actual_cost, currency, created_at
`

type InsertProviderAttemptParams struct {
	ID              string `json:"id"`
	GenerationJobID string `json:"generation_job_id"`
	ProviderID      string `json:"provider_id"`
	AttemptNumber   int32  `json:"attempt_number"`
}

func (q *Queries) InsertProviderAttempt(ctx context.Context, arg InsertProviderAttemptParams) (ProviderAttempt, error) {
	row := q.db.QueryRow(ctx, insertProviderAttempt,
		arg.ID,
		arg.GenerationJobID,
		arg.ProviderID,
		arg.AttemptNumber,
	)
	var i ProviderAttempt
	err := row.Scan(
		&i.ID,
		&i.GenerationJobID,
		&i.ProviderID,
		&i.ModelID,
		&i.ProviderRouteID,
		&i.ProviderRequestID,
		&i.AttemptNumber,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RequestPayloadHash,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LatencyMs,
		&i.EstimatedCost,
		&i.ActualCost,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const markProviderAttemptFailed = `-- name: MarkProviderAttemptFailed :exec
UPDATE provider_attempts
SET status = 'failed',
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    latency_ms = $4
WHERE id = $1
`

type MarkProviderAttemptFailedParams struct {
	ID           string  `json:"id"`
	ErrorCode    *string `json:"error_code"`
	ErrorMessage *string `json:"error_message"`
	LatencyMs    *int32  `json:"latency_ms"`
}

func (q *Queries) MarkProviderAttemptFailed(ctx context.Context, arg MarkProviderAttemptFailedParams) error {
	_, err := q.db.Exec(ctx, markProviderAttemptFailed,
		arg.ID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.LatencyMs,
	)
	return err
}

const markProviderAttemptSucceeded = `-- name: MarkProviderAttemptSucceeded :exec
UPDATE provider_attempts
SET status = 'succeeded',
    completed_at = now(),
    latency_ms = $2
WHERE id = $1
`

type MarkProviderAttemptSucceededParams struct {
	ID        string `json:"id"`
	LatencyMs *int32 `json:"latency_ms"`
}

func (q *Queries) MarkProviderAttemptSucceeded(ctx context.Context, arg MarkProviderAttemptSucceededParams) error {
	_, err := q.db.Exec(ctx, markProviderAttemptSucceeded, arg.ID, arg.LatencyMs)
	return err
}
