// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	// Phase 6A4 supersede concurrency control: a transaction-scoped advisory lock
	// keyed on the exact regeneration slot. Two concurrent forced regenerations of
	// the same slot serialize here, so they compute prior_max_version, archive prior
	// ready rows, and insert the new ready row one at a time — producing versions
	// N+1 and N+2 (never duplicate versions) and leaving exactly one ready row. The
	// lock auto-releases at commit/rollback. The slot key is built deterministically
	// by the caller (internal/assets) from the exact slot identity.
	AcquireSupersedeLock(ctx context.Context, slotKey string) error
	// Phase 6A4 supersede: archive every still-ready row of the exact artifact slot
	// except the just-inserted new asset, linking each forward to it. Slot-scoped and
	// exact — the same predicate as the reuse lookup — so a forced regenerate never
	// archives a compatible/preview neighbor, only the identical slot. Runs in the
	// same transaction (under the slot lock) as the new asset's insert, so committed
	// readers flip atomically from old-ready to new-ready.
	ArchivePriorReadyArtifactSlot(ctx context.Context, arg ArchivePriorReadyArtifactSlotParams) error
	// Phase 6A4 supersede: archive every still-ready row of the exact pack-role slot
	// except the just-inserted new asset, linking each forward to it. Exact and
	// slot-scoped (the FindExactVisualAsset predicate) so a forced pack regenerate
	// never touches a compatible/preview neighbor.
	ArchivePriorReadyVariantSlot(ctx context.Context, arg ArchivePriorReadyVariantSlotParams) error
	// CancelGenerationJob transitions a non-terminal job to cancelled (Phase 7C-1a).
	// The caller validates the source status under LockGenerationJobForUpdate first;
	// this write sets the terminal cancel fields in the same transaction as the
	// reservation release.
	CancelGenerationJob(ctx context.Context, arg CancelGenerationJobParams) (GenerationJob, error)
	// CommitBudgetHold moves a hold's amount from reserved → spent on the budget.
	// GREATEST guards against a negative reserved_amount if accounting ever drifts.
	CommitBudgetHold(ctx context.Context, arg CommitBudgetHoldParams) error
	// CommitReservationForJob flips a reservation reserved → committed exactly
	// once. No row returned means the reservation was not in `reserved` (already
	// committed / released / failed) → caller treats it as a no-op and moves no
	// budget. actual_amount = estimated_amount (Phase 4B: no provider-reported
	// reconciliation).
	CommitReservationForJob(ctx context.Context, generationJobID string) (CommitReservationForJobRow, error)
	// Phase 7C-2: the hard concurrent-job cap counts a token's live generation
	// jobs — those still occupying provider/queue capacity. preview_ready is
	// deliberately included: a preview-ready job is NOT terminal (it may still need
	// final generation), so it still consumes a concurrent slot. completed, failed,
	// and cancelled are terminal and free the slot, so they are excluded. Runs
	// inside the create transaction under the per-token advisory lock so concurrent
	// creates for the same token serialize before counting. Backed by
	// idx_generation_jobs_token_status.
	CountLiveGenerationJobsByToken(ctx context.Context, tokenID string) (int64, error)
	CountProviderAttemptsForJob(ctx context.Context, generationJobID string) (int32, error)
	CreateStyleProfile(ctx context.Context, arg CreateStyleProfileParams) (StyleProfile, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	// Cost-control pre-flight queries (docs/architecture/cost-control.md §3).
	// Phase 4 implements steps 4–7 (price lookup → estimate → budget reservation).
	// EstimateOperationCost loads the active price for (provider × model ×
	// operation) and returns the pre-flight estimate for `units` of work. No row
	// means there is no active price entry → fail closed (no_price_entry).
	EstimateOperationCost(ctx context.Context, arg EstimateOperationCostParams) (EstimateOperationCostRow, error)
	// Phase 6A1 retrieval substrate: the exact-match lookup behind
	// RetrievalResult.exact_match. Owner (tenant/world/visual_identity) + variant
	// + state + style must all match and the asset must be reusable (status =
	// 'ready' — the existing status vocabulary's "active asset"; there is no
	// 'active' status). style_profile_version and quality_tier are optional: when
	// provided they must match exactly. NOTE: quality ordering does not yet exist
	// as a comparable concept in the schema, so quality_tier uses exact equality
	// rather than ">= requested" (documented in internal/assets/retrieval.go).
	// A stable id ASC tie-break keeps the single returned row deterministic when
	// several exact rows exist (e.g. regenerations).
	FindExactVisualAsset(ctx context.Context, arg FindExactVisualAssetParams) (VisualAsset, error)
	// Phase 6A2 single-artifact exact reuse: the narrow deterministic lookup behind
	// the artifact retrieval-before-generation path. Artifacts have no durable
	// visual identity in the generation path (they are asset_type = 'artifact',
	// variant_key = 'default'), so reuse is keyed on the deterministic artifact
	// render hash stored in prompt_hash rather than on identity/matrix retrieval.
	// Owner (tenant/world) + style + quality + the render hash must all match and
	// the asset must be reusable (status = 'ready'). style_profile_version is
	// optional: when provided it must match exactly (the render hash already folds
	// it in, so this is a belt-and-suspenders narrowing). A stable id ASC tie-break
	// keeps the single returned row deterministic when several ready rows share the
	// same hash (e.g. a re-run that raced before this reuse path existed).
	FindReadyArtifactByPromptHash(ctx context.Context, arg FindReadyArtifactByPromptHashParams) (VisualAsset, error)
	GetActiveAPITokenByPrefix(ctx context.Context, tokenPrefix string) (GetActiveAPITokenByPrefixRow, error)
	// Phase 7C-4 (2/2): outbound webhooks. Queries for the per-tenant endpoint
	// config and the per-event delivery-attempt log.
	// The tenant's single active webhook endpoint (the partial unique index
	// guarantees at most one). The repository uses this both to serve the GET
	// config read and to decide insert-vs-update on the PUT upsert.
	GetActiveWebhookEndpointByTenant(ctx context.Context, tenantID string) (WebhookEndpoint, error)
	GetAssetPackByID(ctx context.Context, id string) (GetAssetPackByIDRow, error)
	GetCostBudget(ctx context.Context, id string) (GetCostBudgetRow, error)
	GetGenerationJobByID(ctx context.Context, arg GetGenerationJobByIDParams) (GenerationJob, error)
	GetGenerationJobByIDUnchecked(ctx context.Context, id string) (GenerationJob, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetProviderModelPrice(ctx context.Context, id string) (GetProviderModelPriceRow, error)
	GetStyleProfileByID(ctx context.Context, arg GetStyleProfileByIDParams) (StyleProfile, error)
	GetVisualAssetByID(ctx context.Context, arg GetVisualAssetByIDParams) (VisualAsset, error)
	GetVisualIdentityByID(ctx context.Context, arg GetVisualIdentityByIDParams) (VisualIdentity, error)
	GetVisualIdentityByOwner(ctx context.Context, arg GetVisualIdentityByOwnerParams) (VisualIdentity, error)
	GetVisualIdentityByOwnerForUpdate(ctx context.Context, arg GetVisualIdentityByOwnerForUpdateParams) (VisualIdentity, error)
	// Load one delivery row for the deliver task. Joined with the endpoint by the
	// repository (a second query) so the deliverer has the URL + secret to sign.
	GetWebhookDeliveryByID(ctx context.Context, id string) (WebhookDelivery, error)
	// The endpoint a delivery row targets (the deliverer needs url + secret). Read
	// by id (the delivery carries webhook_endpoint_id) so a later deactivation of
	// the tenant's active endpoint does not strand in-flight deliveries.
	GetWebhookEndpointByID(ctx context.Context, id string) (WebhookEndpoint, error)
	// Pack orchestration queries (Phase 5A, ADR-008). The platform — not the
	// provider adapter — owns pack fan-out: the create transaction inserts the
	// asset_packs row alongside the generation_jobs row, and the worker writes
	// one asset_pack_items row per generated variant.
	// The create transaction inserts the asset_packs row alongside the
	// generation_jobs row. status is a parameter (Phase 6A3): a normal pack that
	// still has roles to generate is inserted 'planned' for the worker to advance,
	// while an all-hits reuse pack is inserted 'completed' directly (no worker run).
	// required_roles/delivered_roles/missing_roles record pack completeness at
	// creation: required = every template role, delivered = roles already satisfied
	// by a reused asset, missing = roles awaiting generation.
	InsertAssetPack(ctx context.Context, arg InsertAssetPackParams) (InsertAssetPackRow, error)
	InsertAssetPackItem(ctx context.Context, arg InsertAssetPackItemParams) error
	// ---------------------------------------------------------------------------
	// Audit events
	// ---------------------------------------------------------------------------
	// InsertAuditEvent records a state-changing admin action. Written in the same
	// transaction as the mutation; if it fails, the mutation fails.
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	// InsertBudgetHold records that `reserved_amount` was credited against
	// `cost_budget_id` for this reservation. Written in the same savepoint as the
	// budget increment so a denied reservation rolls the hold back too. Release /
	// commit reverse exactly the rows recorded here.
	InsertBudgetHold(ctx context.Context, arg InsertBudgetHoldParams) error
	// Phase 6A2 single-artifact exact reuse: insert a generation job that is
	// already terminal (status = 'completed') because an existing ready asset
	// satisfied the request via the deterministic artifact render hash. No provider
	// work runs, so the job carries no cost_reservation_id, a zero estimate, and a
	// zero actual cost — the request is genuinely free. cache_result is fixed to
	// 'exact_match' and final_asset_ids points at the reused asset. This row is
	// never enqueued and the worker never processes it, so the terminal-job
	// finalizer (which would otherwise commit a reservation) is never invoked on it.
	InsertCompletedCacheHitJob(ctx context.Context, arg InsertCompletedCacheHitJobParams) (GenerationJob, error)
	// Phase 6A3 all-hits pack reuse: the pack analogue of InsertCompletedCacheHitJob.
	// Every required role of the pack was satisfied by an existing ready asset, so
	// the pack job is already terminal (status = 'completed') with no provider work:
	// no cost_reservation_id, a zero estimate, a zero actual cost. Unlike the
	// artifact cache-hit (which is always exact_match), a pack aggregates several
	// per-role outcomes, so cache_result is a parameter (the weakest reuse tier
	// across the roles: exact_match | compatible_match | preview_fallback).
	// final_asset_ids points at the reused assets, in role order. This row is never
	// enqueued and the worker never processes it.
	InsertCompletedPackReuseJob(ctx context.Context, arg InsertCompletedPackReuseJobParams) (GenerationJob, error)
	// ---------------------------------------------------------------------------
	// Cost budgets
	// ---------------------------------------------------------------------------
	// InsertCostBudget creates a budget. reserved_amount and spent_amount are
	// platform-owned and start at 0; callers may not set them.
	InsertCostBudget(ctx context.Context, arg InsertCostBudgetParams) (InsertCostBudgetRow, error)
	// InsertCostReservation records the reservation for a job. status=reserved
	// on success; status=failed with failure_reason on no_price_entry /
	// budget_exceeded.
	InsertCostReservation(ctx context.Context, arg InsertCostReservationParams) (CostReservation, error)
	// InsertFinalizerCostEvent writes a cost event carrying estimated/actual when
	// the worker never managed to write one (best-effort fallback).
	InsertFinalizerCostEvent(ctx context.Context, arg InsertFinalizerCostEventParams) error
	InsertGenerationCostEvent(ctx context.Context, arg InsertGenerationCostEventParams) error
	// CONVENTION: queries here list generation_jobs columns EXPLICITLY (not SELECT *).
	// When a migration adds a column, append it to the matching RETURNING/SELECT
	// lists below, or sqlc emits a per-query *Row type and the build breaks.
	InsertGenerationJob(ctx context.Context, arg InsertGenerationJobParams) (GenerationJob, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	// Phase 7B two-phase preview tier. Identical column mapping to InsertVisualAsset
	// but the asset always lands status='preview_ready' (not 'ready'): it is the
	// lighter, earlier output of a preview_first job, committed and observable
	// before the final asset is generated. It is never a reuse target (the artifact
	// reuse lookup matches status='ready' only), so a preview row never satisfies a
	// later request. version is supplied by the caller (the preview path passes 1).
	InsertPreviewVisualAsset(ctx context.Context, arg InsertPreviewVisualAssetParams) (VisualAsset, error)
	InsertProviderAttempt(ctx context.Context, arg InsertProviderAttemptParams) (ProviderAttempt, error)
	// InsertProviderModelPrice creates a new active price entry. effective_from is
	// now(); effective_to is NULL (current).
	InsertProviderModelPrice(ctx context.Context, arg InsertProviderModelPriceParams) (InsertProviderModelPriceRow, error)
	// The new asset always lands status='ready'. version is supplied by the caller
	// (Phase 6A4): the normal generate path passes 1 (the prior schema DEFAULT);
	// a forced regeneration passes prior_max_version + 1 so versions stay monotonic
	// across regenerations of a slot, archived predecessors included.
	InsertVisualAsset(ctx context.Context, arg InsertVisualAssetParams) (VisualAsset, error)
	InsertVisualIdentity(ctx context.Context, arg InsertVisualIdentityParams) (VisualIdentity, error)
	InsertVisualIdentityVersion(ctx context.Context, arg InsertVisualIdentityVersionParams) error
	// Record a freshly emitted event (status = pending, attempt_count = 0). The
	// asynq deliver task re-reads this row by id on every attempt; the queue
	// payload only carries the id.
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error)
	// Create a tenant's active endpoint. The signing secret is server-generated
	// and passed in once here; it is never rewritten on a later URL update (see
	// UpdateWebhookEndpointURL), so a caller that has stored the secret keeps a
	// stable signing key across URL changes.
	InsertWebhookEndpoint(ctx context.Context, arg InsertWebhookEndpointParams) (WebhookEndpoint, error)
	ListAssetPackItems(ctx context.Context, assetPackID string) ([]AssetPackItem, error)
	// ListBudgetsForReservation returns every budget that could apply to a
	// request: the tenant-scope budget(s) plus any token / world / user scoped
	// budgets matching the request's identifiers. The caller picks which to
	// enforce (tenant always; then the narrowest applicable scope).
	ListBudgetsForReservation(ctx context.Context, arg ListBudgetsForReservationParams) ([]ListBudgetsForReservationRow, error)
	ListCostBudgets(ctx context.Context) ([]ListCostBudgetsRow, error)
	// ---------------------------------------------------------------------------
	// Cost reservations (read-only admin list)
	// ---------------------------------------------------------------------------
	ListCostReservationsAdmin(ctx context.Context, arg ListCostReservationsAdminParams) ([]ListCostReservationsAdminRow, error)
	ListProviderModelPrices(ctx context.Context) ([]ListProviderModelPricesRow, error)
	// Provider routing substrate (Phase 7A, internal/providers/routing).
	//
	// ListProviderRoutesForOperation returns every route for an operation joined to
	// its model's status, so the deterministic resolver can filter on active route
	// + active model, match quality/latency tiers and capability, apply provider
	// availability, and tie-break — all in one place it can also unit-test.
	//
	// Prices are deliberately NOT consulted here. Route selection is independent of
	// pricing; the resolved model is then priced at cost-reservation time, where a
	// missing/expired active price surfaces as no_price_entry (422). Keeping the two
	// concerns separate is what lets a request fail with no_route vs no_price_entry
	// for the right reason.
	ListProviderRoutesForOperation(ctx context.Context, operationType string) ([]ListProviderRoutesForOperationRow, error)
	// ListReservedBudgetHolds returns the still-reserved holds for a reservation.
	// Processed once inside the guarded transition; marking each hold committed /
	// released afterwards is belt-and-suspenders against a partial retry.
	ListReservedBudgetHolds(ctx context.Context, costReservationID string) ([]ListReservedBudgetHoldsRow, error)
	ListStyleProfilesByTenant(ctx context.Context, tenantID string) ([]StyleProfile, error)
	// Phase 6A1 retrieval substrate: candidate ready assets for the same owner
	// and visual identity that the compatibility matrix
	// (internal/assets/compatibility.go) may approve as a compatible_match or
	// preview_fallback. State is strict (matrix §7.4/§8.4) so candidates share the
	// requested state_version; style is held constant (same style_profile_id) so a
	// substitution never silently changes the visual style. Identity anchors are
	// excluded here (matrix §10.1: anchors are reference inputs, never display
	// substitutes). Uses idx_visual_assets_identity_variant /
	// idx_visual_assets_identity_family. Deterministic order: fallback_rank ASC
	// (lower = preferred) then id ASC as the final tie-break.
	ListVisualAssetCandidates(ctx context.Context, arg ListVisualAssetCandidatesParams) ([]VisualAsset, error)
	// Phase 6A1 retrieval substrate: a compatibility_tags-optimized candidate
	// lookup over the same owner/identity/state/style scope as
	// ListVisualAssetCandidates, narrowed to assets whose compatibility_tags
	// overlap the requested set (e.g. {generic_presence}). Backed by the GIN index
	// idx_visual_assets_compat_tags. Used when retrieval only needs tag-eligible
	// candidates (and exercised directly by the integration tests). Anchors are
	// excluded; deterministic order matches ListVisualAssetCandidates.
	ListVisualAssetCandidatesByCompatTag(ctx context.Context, arg ListVisualAssetCandidatesByCompatTagParams) ([]VisualAsset, error)
	// LockGenerationJobForUpdate row-locks a job and returns its current status.
	// It is the serialization point that makes in-flight cancel safe (Phase 7C-1):
	// admin cancel and the worker's guarded asset-persist BOTH take this lock on
	// the same row, so whichever commits first wins and the loser observes the
	// committed status. ErrNoRows ⇒ missing or cross-tenant job (→ 404).
	LockGenerationJobForUpdate(ctx context.Context, arg LockGenerationJobForUpdateParams) (string, error)
	// LockGenerationJobRowForUpdate row-locks a job and returns the full row so the
	// retry path can read the persisted resolved route + payload under the same
	// lock it validates and reopens the job with.
	LockGenerationJobRowForUpdate(ctx context.Context, arg LockGenerationJobRowForUpdateParams) (GenerationJob, error)
	// LookupActiveUnitPrice returns the active unit-price components for (provider ×
	// model × operation), independent of quantity (Phase 7C-4 fallback chains). The
	// handler compares these across the resolved chain to keep only same-price-class
	// fallbacks, so the single existing cost reservation stays valid regardless of
	// which route the worker ends up using. No row means there is no active price
	// entry (the primary will fail no_price_entry at reservation anyway).
	LookupActiveUnitPrice(ctx context.Context, arg LookupActiveUnitPriceParams) (LookupActiveUnitPriceRow, error)
	// MarkBudgetHoldStatus records the hold's terminal state. The WHERE guard on
	// status='reserved' makes a re-run a no-op.
	MarkBudgetHoldStatus(ctx context.Context, arg MarkBudgetHoldStatusParams) error
	MarkGenerationJobCompleted(ctx context.Context, arg MarkGenerationJobCompletedParams) (GenerationJob, error)
	MarkGenerationJobFailed(ctx context.Context, arg MarkGenerationJobFailedParams) (GenerationJob, error)
	// Phase 7B two-phase generation: the preview tier landed. Flip the job to
	// preview_ready and record preview_asset_ids. This is committed BEFORE final
	// generation begins (a separate transaction from final persistence) so the
	// preview state is externally observable through the job read and the
	// job-assets read before the final asset exists. final_asset_ids stays empty
	// until MarkGenerationJobCompleted runs after final success.
	MarkGenerationJobPreviewReady(ctx context.Context, arg MarkGenerationJobPreviewReadyParams) (GenerationJob, error)
	MarkGenerationJobRunning(ctx context.Context, arg MarkGenerationJobRunningParams) (GenerationJob, error)
	MarkProviderAttemptFailed(ctx context.Context, arg MarkProviderAttemptFailedParams) error
	MarkProviderAttemptSucceeded(ctx context.Context, arg MarkProviderAttemptSucceededParams) error
	// Cost-reservation terminal lifecycle (docs/architecture/cost-control.md §3
	// steps 9–10). Phase 4B: commit on job success, release on terminal failure.
	// Idempotency lives in the reservation status guard: a reservation moves
	// reserved → committed or reserved → released at most once, and the budget
	// holds are processed only inside that single guarded transition.
	// MarkReservationBudgetExceeded turns a freshly-inserted `reserved` row into a
	// `failed` one when the budget hold is denied. The estimate stays for audit;
	// reserved_amount is zeroed because the savepoint already rolled back every
	// budget increment and hold this reservation made.
	MarkReservationBudgetExceeded(ctx context.Context, arg MarkReservationBudgetExceededParams) error
	// Record the outcome of one delivery attempt: set the terminal/in-progress
	// status, bump attempt_count, and stamp the last HTTP status + error. Called
	// once per asynq attempt (delivered on 2xx, failed otherwise).
	MarkWebhookDeliveryResult(ctx context.Context, arg MarkWebhookDeliveryResultParams) error
	// Phase 6A4 supersede: the current max version across ALL rows (ready AND
	// archived) of the exact artifact reuse slot, so the regenerated asset's version
	// is COALESCE(max, 0) + 1 and stays monotonic even as predecessors are archived.
	// The slot predicate is byte-for-byte the FindReadyArtifactByPromptHash reuse
	// slot minus the status filter (we count archived rows too).
	MaxVersionForArtifactSlot(ctx context.Context, arg MaxVersionForArtifactSlotParams) (int32, error)
	// Phase 6A4 supersede: the current max version across ALL rows (ready AND
	// archived) of the exact pack-role reuse slot. Mirrors MaxVersionForArtifactSlot
	// for the FindExactVisualAsset slot predicate (identity + variant + state + style
	// + quality), minus the status filter.
	MaxVersionForVariantSlot(ctx context.Context, arg MaxVersionForVariantSlotParams) (int32, error)
	// ReleaseBudgetHold returns a hold's amount to the budget: drop reserved,
	// leave spent untouched.
	ReleaseBudgetHold(ctx context.Context, arg ReleaseBudgetHoldParams) error
	// ReleaseReservationForJob flips a reservation reserved → released exactly
	// once. actual_amount stays NULL (job failed, nothing charged). No row
	// returned → no-op.
	ReleaseReservationForJob(ctx context.Context, generationJobID string) (ReleaseReservationForJobRow, error)
	// ReserveActiveBudget atomically holds `amount` against an active budget.
	// The conditional WHERE is the consistency point: concurrent requests that
	// would collectively oversell the limit see all-but-one fail (no row
	// returned → budget_exceeded).
	ReserveActiveBudget(ctx context.Context, arg ReserveActiveBudgetParams) (string, error)
	// ReservePausedBudget records a hold against a paused budget without
	// enforcing the limit (paused = recording only; never deny).
	ReservePausedBudget(ctx context.Context, arg ReservePausedBudgetParams) (string, error)
	// ResetBudgetPeriodIfElapsed lazily rolls a budget over to its current UTC
	// window (Phase 7C-1c). It runs inside the reservation transaction, before the
	// limit is enforced, so a daily/monthly budget whose window has elapsed starts
	// the new period clean:
	//   - advance period_start to the current window start
	//   - zero spent_amount
	//   - clear an `exceeded` status back to `active` (paused stays paused)
	//   - reserved_amount is left untouched, so a live hold opened just before the
	//     reset survives until its job terminates.
	// The WHERE period_start < <window start> guard makes the reset idempotent: two
	// concurrent reservations serialize on the row lock the UPDATE takes, and only
	// the first (whose period_start is still behind the window) actually resets.
	// The window start is computed in UTC from now() so no clock is injected.
	ResetBudgetPeriodIfElapsed(ctx context.Context, id string) (int64, error)
	// RetryResetGenerationJob reopens a failed job (Phase 7C-1b). It keeps the job
	// identity, payload, fallback policy, delivery mode, persisted resolved route,
	// and preview_asset_ids, but clears the terminal failure fields and the run
	// timestamps, links the fresh cost reservation + estimate, and clears
	// final_asset_ids so a prior failed-final attempt leaves no stale final output.
	// The caller validates the source status is 'failed' under
	// LockGenerationJobForUpdate and reserves cost in the same transaction.
	RetryResetGenerationJob(ctx context.Context, arg RetryResetGenerationJobParams) (GenerationJob, error)
	// SetGenerationJobActualCost records the committed actual on the job row.
	SetGenerationJobActualCost(ctx context.Context, arg SetGenerationJobActualCostParams) error
	// SetGenerationJobAssetPack links the job to the pack it created. Run inside
	// the create transaction, after both rows exist.
	SetGenerationJobAssetPack(ctx context.Context, arg SetGenerationJobAssetPackParams) error
	// SetGenerationJobCost links a job to its cost_reservation and records the
	// pre-flight estimate. Run inside the create transaction, after the
	// reservation row exists.
	SetGenerationJobCost(ctx context.Context, arg SetGenerationJobCostParams) error
	// Admin cost surface (docs/architecture/admin-control-surface.md §"Cost
	// controls"). Phase 4B: price-book create/list/get/update, cost-budget
	// create/list/update, cost-reservation list, and the audit-event write that
	// every mutation shares a transaction with.
	// ---------------------------------------------------------------------------
	// Price book
	// ---------------------------------------------------------------------------
	// SupersedePreviousActivePrice ends the current active entry for a
	// (provider × model × operation_type): clears is_active and stamps
	// effective_to. Run in the same transaction as the new INSERT so there is
	// never a window with zero (or two) active rows. :execrows reports whether an
	// entry was actually superseded.
	SupersedePreviousActivePrice(ctx context.Context, arg SupersedePreviousActivePriceParams) (int64, error)
	TouchAPITokenLastUsed(ctx context.Context, id string) error
	// UpdateAssetPackCompleteness records the final delivered-vs-missing required
	// roles a pack run resolved to (Phase 6A3). The worker calls it at the terminal
	// step so a consumer can read pack completeness off asset_packs directly.
	UpdateAssetPackCompleteness(ctx context.Context, arg UpdateAssetPackCompletenessParams) error
	UpdateAssetPackStatus(ctx context.Context, arg UpdateAssetPackStatusParams) error
	// UpdateCostBudget mutates only limit_amount and status. reserved_amount,
	// spent_amount, period_start, and the scope/period identity stay platform-owned
	// and fixed (period_start advances only via the lazy reservation-time reset).
	UpdateCostBudget(ctx context.Context, arg UpdateCostBudgetParams) (UpdateCostBudgetRow, error)
	// UpdateLatestJobCostEvent stamps the estimated/actual cost and final status
	// onto the most recent cost event for a job (the one the worker wrote for the
	// terminal attempt). Returns the number of rows touched so the finalizer can
	// insert one if the worker never wrote it.
	UpdateLatestJobCostEvent(ctx context.Context, arg UpdateLatestJobCostEventParams) (int64, error)
	// UpdateProviderModelPrice mutates only the editable fields (effective_to,
	// is_active, notes). COALESCE keeps unspecified fields unchanged.
	UpdateProviderModelPrice(ctx context.Context, arg UpdateProviderModelPriceParams) (UpdateProviderModelPriceRow, error)
	UpdateVisualIdentityWithVersionBump(ctx context.Context, arg UpdateVisualIdentityWithVersionBumpParams) (VisualIdentity, error)
	// Change the URL of the tenant's active endpoint, preserving the existing
	// signing secret. Used by the upsert when a Get already found an active row.
	// The tenant_id predicate is app-level defense-in-depth alongside the Phase
	// 7C-3 RLS policy (which already scopes the row to app.current_tenant).
	UpdateWebhookEndpointURL(ctx context.Context, arg UpdateWebhookEndpointURLParams) (WebhookEndpoint, error)
}

var _ Querier = (*Queries)(nil)
