// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: style_profiles.sql

package dbgen

import (
	"context"
)

const createStyleProfile = `-- name: CreateStyleProfile :one
INSERT INTO style_profiles (
    id, tenant_id, world_id, name, style_mode,
    positive_prompt, negative_prompt, default_quality_tier, status
) VALUES (
    $1, $2, NULL, $3, $4,
    $5, $6, $7, 'active'
)
RETURNING id, tenant_id, world_id, name, style_mode, style_profile_version,
          positive_prompt, negative_prompt, loras, reference_style_asset_ids,
          default_quality_tier, status, metadata, created_at, updated_at
`

type CreateStyleProfileParams struct {
	ID                 string  `json:"id"`
	TenantID           string  `json:"tenant_id"`
	Name               string  `json:"name"`
	StyleMode          string  `json:"style_mode"`
	PositivePrompt     string  `json:"positive_prompt"`
	NegativePrompt     *string `json:"negative_prompt"`
	DefaultQualityTier string  `json:"default_quality_tier"`
}

func (q *Queries) CreateStyleProfile(ctx context.Context, arg CreateStyleProfileParams) (StyleProfile, error) {
	row := q.db.QueryRow(ctx, createStyleProfile,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.StyleMode,
		arg.PositivePrompt,
		arg.NegativePrompt,
		arg.DefaultQualityTier,
	)
	var i StyleProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.Name,
		&i.StyleMode,
		&i.StyleProfileVersion,
		&i.PositivePrompt,
		&i.NegativePrompt,
		&i.Loras,
		&i.ReferenceStyleAssetIds,
		&i.DefaultQualityTier,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStyleProfileByID = `-- name: GetStyleProfileByID :one
SELECT id, tenant_id, world_id, name, style_mode, style_profile_version,
       positive_prompt, negative_prompt, loras, reference_style_asset_ids,
       default_quality_tier, status, metadata, created_at, updated_at
FROM style_profiles
WHERE id = $1
  AND tenant_id = $2
  AND status = 'active'
`

type GetStyleProfileByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetStyleProfileByID(ctx context.Context, arg GetStyleProfileByIDParams) (StyleProfile, error) {
	row := q.db.QueryRow(ctx, getStyleProfileByID, arg.ID, arg.TenantID)
	var i StyleProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.Name,
		&i.StyleMode,
		&i.StyleProfileVersion,
		&i.PositivePrompt,
		&i.NegativePrompt,
		&i.Loras,
		&i.ReferenceStyleAssetIds,
		&i.DefaultQualityTier,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStyleProfilesByTenant = `-- name: ListStyleProfilesByTenant :many
SELECT id, tenant_id, world_id, name, style_mode, style_profile_version,
       positive_prompt, negative_prompt, loras, reference_style_asset_ids,
       default_quality_tier, status, metadata, created_at, updated_at
FROM style_profiles
WHERE tenant_id = $1
  AND status = 'active'
  AND world_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListStyleProfilesByTenant(ctx context.Context, tenantID string) ([]StyleProfile, error) {
	rows, err := q.db.Query(ctx, listStyleProfilesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StyleProfile
	for rows.Next() {
		var i StyleProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorldID,
			&i.Name,
			&i.StyleMode,
			&i.StyleProfileVersion,
			&i.PositivePrompt,
			&i.NegativePrompt,
			&i.Loras,
			&i.ReferenceStyleAssetIds,
			&i.DefaultQualityTier,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
