// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: visual_identities.sql

package dbgen

import (
	"context"
)

const getVisualIdentityByID = `-- name: GetVisualIdentityByID :one
SELECT id, tenant_id, world_id, owner_type, owner_id, display_name,
       canonical_visual_traits, allowed_variation, forbidden_drift,
       style_profile_id, consistency_key, identity_seed,
       anchor_asset_ids, reference_asset_ids,
       current_version, current_state_version, status,
       created_at, updated_at
FROM visual_identities
WHERE id = $1
  AND tenant_id = $2
`

type GetVisualIdentityByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetVisualIdentityByID(ctx context.Context, arg GetVisualIdentityByIDParams) (VisualIdentity, error) {
	row := q.db.QueryRow(ctx, getVisualIdentityByID, arg.ID, arg.TenantID)
	var i VisualIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.OwnerType,
		&i.OwnerID,
		&i.DisplayName,
		&i.CanonicalVisualTraits,
		&i.AllowedVariation,
		&i.ForbiddenDrift,
		&i.StyleProfileID,
		&i.ConsistencyKey,
		&i.IdentitySeed,
		&i.AnchorAssetIds,
		&i.ReferenceAssetIds,
		&i.CurrentVersion,
		&i.CurrentStateVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisualIdentityByOwner = `-- name: GetVisualIdentityByOwner :one
SELECT id, tenant_id, world_id, owner_type, owner_id, display_name,
       canonical_visual_traits, allowed_variation, forbidden_drift,
       style_profile_id, consistency_key, identity_seed,
       anchor_asset_ids, reference_asset_ids,
       current_version, current_state_version, status,
       created_at, updated_at
FROM visual_identities
WHERE tenant_id = $1
  AND world_id = $2
  AND owner_type = $3
  AND owner_id = $4
`

type GetVisualIdentityByOwnerParams struct {
	TenantID  string `json:"tenant_id"`
	WorldID   string `json:"world_id"`
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) GetVisualIdentityByOwner(ctx context.Context, arg GetVisualIdentityByOwnerParams) (VisualIdentity, error) {
	row := q.db.QueryRow(ctx, getVisualIdentityByOwner,
		arg.TenantID,
		arg.WorldID,
		arg.OwnerType,
		arg.OwnerID,
	)
	var i VisualIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.OwnerType,
		&i.OwnerID,
		&i.DisplayName,
		&i.CanonicalVisualTraits,
		&i.AllowedVariation,
		&i.ForbiddenDrift,
		&i.StyleProfileID,
		&i.ConsistencyKey,
		&i.IdentitySeed,
		&i.AnchorAssetIds,
		&i.ReferenceAssetIds,
		&i.CurrentVersion,
		&i.CurrentStateVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisualIdentityByOwnerForUpdate = `-- name: GetVisualIdentityByOwnerForUpdate :one
SELECT id, tenant_id, world_id, owner_type, owner_id, display_name,
       canonical_visual_traits, allowed_variation, forbidden_drift,
       style_profile_id, consistency_key, identity_seed,
       anchor_asset_ids, reference_asset_ids,
       current_version, current_state_version, status,
       created_at, updated_at
FROM visual_identities
WHERE tenant_id = $1
  AND world_id = $2
  AND owner_type = $3
  AND owner_id = $4
FOR UPDATE
`

type GetVisualIdentityByOwnerForUpdateParams struct {
	TenantID  string `json:"tenant_id"`
	WorldID   string `json:"world_id"`
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) GetVisualIdentityByOwnerForUpdate(ctx context.Context, arg GetVisualIdentityByOwnerForUpdateParams) (VisualIdentity, error) {
	row := q.db.QueryRow(ctx, getVisualIdentityByOwnerForUpdate,
		arg.TenantID,
		arg.WorldID,
		arg.OwnerType,
		arg.OwnerID,
	)
	var i VisualIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.OwnerType,
		&i.OwnerID,
		&i.DisplayName,
		&i.CanonicalVisualTraits,
		&i.AllowedVariation,
		&i.ForbiddenDrift,
		&i.StyleProfileID,
		&i.ConsistencyKey,
		&i.IdentitySeed,
		&i.AnchorAssetIds,
		&i.ReferenceAssetIds,
		&i.CurrentVersion,
		&i.CurrentStateVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVisualIdentity = `-- name: InsertVisualIdentity :one
INSERT INTO visual_identities (
    id, tenant_id, world_id, owner_type, owner_id, display_name,
    canonical_visual_traits, style_profile_id, consistency_key,
    current_version, status
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    1, 'active'
)
RETURNING id, tenant_id, world_id, owner_type, owner_id, display_name,
          canonical_visual_traits, allowed_variation, forbidden_drift,
          style_profile_id, consistency_key, identity_seed,
          anchor_asset_ids, reference_asset_ids,
          current_version, current_state_version, status,
          created_at, updated_at
`

type InsertVisualIdentityParams struct {
	ID                    string  `json:"id"`
	TenantID              string  `json:"tenant_id"`
	WorldID               string  `json:"world_id"`
	OwnerType             string  `json:"owner_type"`
	OwnerID               string  `json:"owner_id"`
	DisplayName           string  `json:"display_name"`
	CanonicalVisualTraits []byte  `json:"canonical_visual_traits"`
	StyleProfileID        string  `json:"style_profile_id"`
	ConsistencyKey        *string `json:"consistency_key"`
}

func (q *Queries) InsertVisualIdentity(ctx context.Context, arg InsertVisualIdentityParams) (VisualIdentity, error) {
	row := q.db.QueryRow(ctx, insertVisualIdentity,
		arg.ID,
		arg.TenantID,
		arg.WorldID,
		arg.OwnerType,
		arg.OwnerID,
		arg.DisplayName,
		arg.CanonicalVisualTraits,
		arg.StyleProfileID,
		arg.ConsistencyKey,
	)
	var i VisualIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.OwnerType,
		&i.OwnerID,
		&i.DisplayName,
		&i.CanonicalVisualTraits,
		&i.AllowedVariation,
		&i.ForbiddenDrift,
		&i.StyleProfileID,
		&i.ConsistencyKey,
		&i.IdentitySeed,
		&i.AnchorAssetIds,
		&i.ReferenceAssetIds,
		&i.CurrentVersion,
		&i.CurrentStateVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVisualIdentityVersion = `-- name: InsertVisualIdentityVersion :exec
INSERT INTO visual_identity_versions (
    visual_identity_id, version, reason, canonical_traits_snapshot
) VALUES (
    $1, $2, $3, $4
)
`

type InsertVisualIdentityVersionParams struct {
	VisualIdentityID        string `json:"visual_identity_id"`
	Version                 int32  `json:"version"`
	Reason                  string `json:"reason"`
	CanonicalTraitsSnapshot []byte `json:"canonical_traits_snapshot"`
}

func (q *Queries) InsertVisualIdentityVersion(ctx context.Context, arg InsertVisualIdentityVersionParams) error {
	_, err := q.db.Exec(ctx, insertVisualIdentityVersion,
		arg.VisualIdentityID,
		arg.Version,
		arg.Reason,
		arg.CanonicalTraitsSnapshot,
	)
	return err
}

const updateVisualIdentityWithVersionBump = `-- name: UpdateVisualIdentityWithVersionBump :one
UPDATE visual_identities
SET display_name = $2,
    canonical_visual_traits = $3,
    style_profile_id = $4,
    consistency_key = $5,
    current_version = current_version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, world_id, owner_type, owner_id, display_name,
          canonical_visual_traits, allowed_variation, forbidden_drift,
          style_profile_id, consistency_key, identity_seed,
          anchor_asset_ids, reference_asset_ids,
          current_version, current_state_version, status,
          created_at, updated_at
`

type UpdateVisualIdentityWithVersionBumpParams struct {
	ID                    string  `json:"id"`
	DisplayName           string  `json:"display_name"`
	CanonicalVisualTraits []byte  `json:"canonical_visual_traits"`
	StyleProfileID        string  `json:"style_profile_id"`
	ConsistencyKey        *string `json:"consistency_key"`
}

func (q *Queries) UpdateVisualIdentityWithVersionBump(ctx context.Context, arg UpdateVisualIdentityWithVersionBumpParams) (VisualIdentity, error) {
	row := q.db.QueryRow(ctx, updateVisualIdentityWithVersionBump,
		arg.ID,
		arg.DisplayName,
		arg.CanonicalVisualTraits,
		arg.StyleProfileID,
		arg.ConsistencyKey,
	)
	var i VisualIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorldID,
		&i.OwnerType,
		&i.OwnerID,
		&i.DisplayName,
		&i.CanonicalVisualTraits,
		&i.AllowedVariation,
		&i.ForbiddenDrift,
		&i.StyleProfileID,
		&i.ConsistencyKey,
		&i.IdentitySeed,
		&i.AnchorAssetIds,
		&i.ReferenceAssetIds,
		&i.CurrentVersion,
		&i.CurrentStateVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
