// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhooks.sql

package dbgen

import (
	"context"
)

const getActiveWebhookEndpointByTenant = `-- name: GetActiveWebhookEndpointByTenant :one

SELECT id, tenant_id, url, secret, is_active, created_at, updated_at
FROM webhook_endpoints
WHERE tenant_id = $1
  AND is_active = true
`

// Phase 7C-4 (2/2): outbound webhooks. Queries for the per-tenant endpoint
// config and the per-event delivery-attempt log.
// The tenant's single active webhook endpoint (the partial unique index
// guarantees at most one). The repository uses this both to serve the GET
// config read and to decide insert-vs-update on the PUT upsert.
func (q *Queries) GetActiveWebhookEndpointByTenant(ctx context.Context, tenantID string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getActiveWebhookEndpointByTenant, tenantID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDeliveryByID = `-- name: GetWebhookDeliveryByID :one
SELECT id, tenant_id, webhook_endpoint_id, event_type, generation_job_id,
       payload, status, attempt_count, last_http_status, last_error,
       created_at, updated_at
FROM webhook_deliveries
WHERE id = $1
`

// Load one delivery row for the deliver task. Joined with the endpoint by the
// repository (a second query) so the deliverer has the URL + secret to sign.
func (q *Queries) GetWebhookDeliveryByID(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WebhookEndpointID,
		&i.EventType,
		&i.GenerationJobID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.LastHttpStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, tenant_id, url, secret, is_active, created_at, updated_at
FROM webhook_endpoints
WHERE id = $1
`

// The endpoint a delivery row targets (the deliverer needs url + secret). Read
// by id (the delivery carries webhook_endpoint_id) so a later deactivation of
// the tenant's active endpoint does not strand in-flight deliveries.
func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (
    id, tenant_id, webhook_endpoint_id, event_type, generation_job_id, payload, status, attempt_count
) VALUES (
    $1, $2, $3, $4, $5, $6, 'pending', 0
)
RETURNING id, tenant_id, webhook_endpoint_id, event_type, generation_job_id,
          payload, status, attempt_count, last_http_status, last_error,
          created_at, updated_at
`

type InsertWebhookDeliveryParams struct {
	ID                string  `json:"id"`
	TenantID          string  `json:"tenant_id"`
	WebhookEndpointID string  `json:"webhook_endpoint_id"`
	EventType         string  `json:"event_type"`
	GenerationJobID   *string `json:"generation_job_id"`
	Payload           []byte  `json:"payload"`
}

// Record a freshly emitted event (status = pending, attempt_count = 0). The
// asynq deliver task re-reads this row by id on every attempt; the queue
// payload only carries the id.
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.ID,
		arg.TenantID,
		arg.WebhookEndpointID,
		arg.EventType,
		arg.GenerationJobID,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WebhookEndpointID,
		&i.EventType,
		&i.GenerationJobID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.LastHttpStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookEndpoint = `-- name: InsertWebhookEndpoint :one
INSERT INTO webhook_endpoints (
    id, tenant_id, url, secret
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, tenant_id, url, secret, is_active, created_at, updated_at
`

type InsertWebhookEndpointParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Url      string `json:"url"`
	Secret   string `json:"secret"`
}

// Create a tenant's active endpoint. The signing secret is server-generated
// and passed in once here; it is never rewritten on a later URL update (see
// UpdateWebhookEndpointURL), so a caller that has stored the secret keeps a
// stable signing key across URL changes.
func (q *Queries) InsertWebhookEndpoint(ctx context.Context, arg InsertWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, insertWebhookEndpoint,
		arg.ID,
		arg.TenantID,
		arg.Url,
		arg.Secret,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliveryResult = `-- name: MarkWebhookDeliveryResult :exec
UPDATE webhook_deliveries
SET status = $2,
    attempt_count = attempt_count + 1,
    last_http_status = $3,
    last_error = $4,
    updated_at = now()
WHERE id = $1
`

type MarkWebhookDeliveryResultParams struct {
	ID             string  `json:"id"`
	Status         string  `json:"status"`
	LastHttpStatus *int32  `json:"last_http_status"`
	LastError      *string `json:"last_error"`
}

// Record the outcome of one delivery attempt: set the terminal/in-progress
// status, bump attempt_count, and stamp the last HTTP status + error. Called
// once per asynq attempt (delivered on 2xx, failed otherwise).
func (q *Queries) MarkWebhookDeliveryResult(ctx context.Context, arg MarkWebhookDeliveryResultParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryResult,
		arg.ID,
		arg.Status,
		arg.LastHttpStatus,
		arg.LastError,
	)
	return err
}

const updateWebhookEndpointURL = `-- name: UpdateWebhookEndpointURL :one
UPDATE webhook_endpoints
SET url = $2,
    updated_at = now()
WHERE id = $1
  AND is_active = true
RETURNING id, tenant_id, url, secret, is_active, created_at, updated_at
`

type UpdateWebhookEndpointURLParams struct {
	ID  string `json:"id"`
	Url string `json:"url"`
}

// Change the URL of the tenant's active endpoint, preserving the existing
// signing secret. Used by the upsert when a Get already found an active row.
func (q *Queries) UpdateWebhookEndpointURL(ctx context.Context, arg UpdateWebhookEndpointURLParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpointURL, arg.ID, arg.Url)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
