package webhooks

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	appdb "github.com/zakkriel/drchat-image-platform/internal/db"
	"github.com/zakkriel/drchat-image-platform/internal/db/dbgen"
)

// ErrNotFound is returned when a tenant has no active endpoint, or a delivery /
// endpoint row does not exist. Handlers and the deliverer map it to a 404 / a
// clean no-op respectively.
var ErrNotFound = errors.New("webhooks: not found")

// Endpoint is the domain view of a tenant's active webhook config. The secret
// is included so the config handler can return it on create and the deliverer
// can sign with it; read callers that must not leak it (the GET config read)
// drop it at the response boundary.
type Endpoint struct {
	ID       string
	TenantID string
	URL      string
	Secret   string
	IsActive bool
}

// Delivery is the domain view of one delivery-attempt log row. Payload is the
// exact event JSON bytes that were enqueued; the deliverer signs and posts
// these bytes verbatim so the signature matches what the receiver sees.
type Delivery struct {
	ID                string
	TenantID          string
	WebhookEndpointID string
	EventType         string
	GenerationJobID   *string
	Payload           []byte
	Status            string
	AttemptCount      int32
}

// InsertEndpointParams creates a tenant's active endpoint. The secret is
// server-generated by the caller (the config handler) and set once.
type InsertEndpointParams struct {
	ID       string
	TenantID string
	URL      string
	Secret   string
}

// InsertDeliveryParams records a freshly emitted event as pending.
type InsertDeliveryParams struct {
	ID                string
	TenantID          string
	WebhookEndpointID string
	EventType         string
	GenerationJobID   *string
	Payload           []byte
}

// DeliveryResult is the outcome of one delivery attempt, persisted by the
// deliverer after each POST. HTTPStatus is 0 on a transport error.
type DeliveryResult struct {
	DeliveryID string
	Status     string
	HTTPStatus int
	Err        string
}

// Repository is the narrow persistence interface the Emitter and Deliverer
// depend on. Keeping it small lets both be unit-tested with a fake (no DB).
type Repository interface {
	// GetActiveEndpointByTenant returns the tenant's single active endpoint, or
	// ErrNotFound when the tenant has none.
	GetActiveEndpointByTenant(ctx context.Context, tenantID string) (Endpoint, error)
	// GetEndpointByID returns an endpoint by id (the deliverer resolves the
	// endpoint a delivery targets), or ErrNotFound.
	GetEndpointByID(ctx context.Context, id string) (Endpoint, error)
	// InsertEndpoint creates a tenant's active endpoint with a fixed secret.
	InsertEndpoint(ctx context.Context, params InsertEndpointParams) (Endpoint, error)
	// UpdateEndpointURL changes an active endpoint's URL, preserving its secret.
	// tenantID scopes the write under RLS (app.current_tenant) and as an
	// app-level predicate.
	UpdateEndpointURL(ctx context.Context, id, tenantID, url string) (Endpoint, error)
	// InsertDelivery records a pending delivery for an emitted event.
	InsertDelivery(ctx context.Context, params InsertDeliveryParams) (Delivery, error)
	// GetDeliveryByID loads one delivery row, or ErrNotFound.
	GetDeliveryByID(ctx context.Context, id string) (Delivery, error)
	// MarkDeliveryResult records the outcome of one attempt (status, attempt++,
	// last HTTP status, last error).
	MarkDeliveryResult(ctx context.Context, res DeliveryResult) error
}

type pgRepository struct {
	pool *pgxpool.Pool
}

// NewRepository wraps the sqlc queries over a connection pool (Phase 7C-3
// RLS-aware; mirrors internal/styles/repository.go).
//
// Pool choice is the caller's: the config surface (PUT/GET
// /v1/admin/webhook-endpoint) constructs this over the TENANT pool, so its
// tenant-scoped methods run inside a tenant executor (app.current_tenant set)
// and webhook_endpoints RLS enforces isolation. The worker constructs it over
// the SYSTEM (BYPASSRLS) pool, where the by-id deliverer reads/writes and the
// emitter's pending-delivery insert run without a GUC.
//
// Tenant-scoped methods (GetActiveEndpointByTenant, InsertEndpoint,
// UpdateEndpointURL) wrap appdb.WithTenant so they are correct on the tenant
// pool; on a BYPASSRLS pool the GUC is harmless. By-id / system methods
// (GetEndpointByID, GetDeliveryByID, MarkDeliveryResult, InsertDelivery) run
// plain — they are only ever called on the system pool (the worker), which is
// not subject to RLS.
func NewRepository(pool *pgxpool.Pool) Repository {
	return &pgRepository{pool: pool}
}

func (r *pgRepository) GetActiveEndpointByTenant(ctx context.Context, tenantID string) (Endpoint, error) {
	var out Endpoint
	err := appdb.WithTenant(ctx, r.pool, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		row, err := dbgen.New(tx).GetActiveWebhookEndpointByTenant(ctx, tenantID)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return ErrNotFound
			}
			return err
		}
		out = endpointFromRow(row)
		return nil
	})
	if err != nil {
		return Endpoint{}, err
	}
	return out, nil
}

func (r *pgRepository) GetEndpointByID(ctx context.Context, id string) (Endpoint, error) {
	row, err := dbgen.New(r.pool).GetWebhookEndpointByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Endpoint{}, ErrNotFound
		}
		return Endpoint{}, err
	}
	return endpointFromRow(row), nil
}

func (r *pgRepository) InsertEndpoint(ctx context.Context, params InsertEndpointParams) (Endpoint, error) {
	var out Endpoint
	err := appdb.WithTenant(ctx, r.pool, params.TenantID, func(ctx context.Context, tx pgx.Tx) error {
		row, err := dbgen.New(tx).InsertWebhookEndpoint(ctx, dbgen.InsertWebhookEndpointParams{
			ID:       params.ID,
			TenantID: params.TenantID,
			Url:      params.URL,
			Secret:   params.Secret,
		})
		if err != nil {
			return err
		}
		out = endpointFromRow(row)
		return nil
	})
	if err != nil {
		return Endpoint{}, err
	}
	return out, nil
}

func (r *pgRepository) UpdateEndpointURL(ctx context.Context, id, tenantID, url string) (Endpoint, error) {
	var out Endpoint
	err := appdb.WithTenant(ctx, r.pool, tenantID, func(ctx context.Context, tx pgx.Tx) error {
		row, err := dbgen.New(tx).UpdateWebhookEndpointURL(ctx, dbgen.UpdateWebhookEndpointURLParams{
			ID:       id,
			TenantID: tenantID,
			Url:      url,
		})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return ErrNotFound
			}
			return err
		}
		out = endpointFromRow(row)
		return nil
	})
	if err != nil {
		return Endpoint{}, err
	}
	return out, nil
}

func (r *pgRepository) InsertDelivery(ctx context.Context, params InsertDeliveryParams) (Delivery, error) {
	row, err := dbgen.New(r.pool).InsertWebhookDelivery(ctx, dbgen.InsertWebhookDeliveryParams{
		ID:                params.ID,
		TenantID:          params.TenantID,
		WebhookEndpointID: params.WebhookEndpointID,
		EventType:         params.EventType,
		GenerationJobID:   params.GenerationJobID,
		Payload:           params.Payload,
	})
	if err != nil {
		return Delivery{}, err
	}
	return deliveryFromRow(row), nil
}

func (r *pgRepository) GetDeliveryByID(ctx context.Context, id string) (Delivery, error) {
	row, err := dbgen.New(r.pool).GetWebhookDeliveryByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Delivery{}, ErrNotFound
		}
		return Delivery{}, err
	}
	return deliveryFromRow(row), nil
}

func (r *pgRepository) MarkDeliveryResult(ctx context.Context, res DeliveryResult) error {
	var httpStatus *int32
	if res.HTTPStatus != 0 {
		s := int32(res.HTTPStatus)
		httpStatus = &s
	}
	var lastErr *string
	if res.Err != "" {
		e := res.Err
		lastErr = &e
	}
	return dbgen.New(r.pool).MarkWebhookDeliveryResult(ctx, dbgen.MarkWebhookDeliveryResultParams{
		ID:             res.DeliveryID,
		Status:         res.Status,
		LastHttpStatus: httpStatus,
		LastError:      lastErr,
	})
}

func endpointFromRow(row dbgen.WebhookEndpoint) Endpoint {
	return Endpoint{
		ID:       row.ID,
		TenantID: row.TenantID,
		URL:      row.Url,
		Secret:   row.Secret,
		IsActive: row.IsActive,
	}
}

func deliveryFromRow(row dbgen.WebhookDelivery) Delivery {
	return Delivery{
		ID:                row.ID,
		TenantID:          row.TenantID,
		WebhookEndpointID: row.WebhookEndpointID,
		EventType:         row.EventType,
		GenerationJobID:   row.GenerationJobID,
		Payload:           row.Payload,
		Status:            row.Status,
		AttemptCount:      row.AttemptCount,
	}
}
