package webhooks

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/zakkriel/drchat-image-platform/internal/db/dbgen"
)

// ErrNotFound is returned when a tenant has no active endpoint, or a delivery /
// endpoint row does not exist. Handlers and the deliverer map it to a 404 / a
// clean no-op respectively.
var ErrNotFound = errors.New("webhooks: not found")

// Endpoint is the domain view of a tenant's active webhook config. The secret
// is included so the config handler can return it on create and the deliverer
// can sign with it; read callers that must not leak it (the GET config read)
// drop it at the response boundary.
type Endpoint struct {
	ID       string
	TenantID string
	URL      string
	Secret   string
	IsActive bool
}

// Delivery is the domain view of one delivery-attempt log row. Payload is the
// exact event JSON bytes that were enqueued; the deliverer signs and posts
// these bytes verbatim so the signature matches what the receiver sees.
type Delivery struct {
	ID                string
	TenantID          string
	WebhookEndpointID string
	EventType         string
	GenerationJobID   *string
	Payload           []byte
	Status            string
	AttemptCount      int32
}

// InsertEndpointParams creates a tenant's active endpoint. The secret is
// server-generated by the caller (the config handler) and set once.
type InsertEndpointParams struct {
	ID       string
	TenantID string
	URL      string
	Secret   string
}

// InsertDeliveryParams records a freshly emitted event as pending.
type InsertDeliveryParams struct {
	ID                string
	TenantID          string
	WebhookEndpointID string
	EventType         string
	GenerationJobID   *string
	Payload           []byte
}

// DeliveryResult is the outcome of one delivery attempt, persisted by the
// deliverer after each POST. HTTPStatus is 0 on a transport error.
type DeliveryResult struct {
	DeliveryID string
	Status     string
	HTTPStatus int
	Err        string
}

// Repository is the narrow persistence interface the Emitter and Deliverer
// depend on. Keeping it small lets both be unit-tested with a fake (no DB).
type Repository interface {
	// GetActiveEndpointByTenant returns the tenant's single active endpoint, or
	// ErrNotFound when the tenant has none.
	GetActiveEndpointByTenant(ctx context.Context, tenantID string) (Endpoint, error)
	// GetEndpointByID returns an endpoint by id (the deliverer resolves the
	// endpoint a delivery targets), or ErrNotFound.
	GetEndpointByID(ctx context.Context, id string) (Endpoint, error)
	// InsertEndpoint creates a tenant's active endpoint with a fixed secret.
	InsertEndpoint(ctx context.Context, params InsertEndpointParams) (Endpoint, error)
	// UpdateEndpointURL changes an active endpoint's URL, preserving its secret.
	UpdateEndpointURL(ctx context.Context, id, url string) (Endpoint, error)
	// InsertDelivery records a pending delivery for an emitted event.
	InsertDelivery(ctx context.Context, params InsertDeliveryParams) (Delivery, error)
	// GetDeliveryByID loads one delivery row, or ErrNotFound.
	GetDeliveryByID(ctx context.Context, id string) (Delivery, error)
	// MarkDeliveryResult records the outcome of one attempt (status, attempt++,
	// last HTTP status, last error).
	MarkDeliveryResult(ctx context.Context, res DeliveryResult) error
}

type pgRepository struct {
	q *dbgen.Queries
}

// NewRepository wraps the sqlc queries over a connection pool. Mirrors the
// other internal repositories (e.g. internal/styles/repository.go).
func NewRepository(pool *pgxpool.Pool) Repository {
	return &pgRepository{q: dbgen.New(pool)}
}

func (r *pgRepository) GetActiveEndpointByTenant(ctx context.Context, tenantID string) (Endpoint, error) {
	row, err := r.q.GetActiveWebhookEndpointByTenant(ctx, tenantID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Endpoint{}, ErrNotFound
		}
		return Endpoint{}, err
	}
	return endpointFromRow(row), nil
}

func (r *pgRepository) GetEndpointByID(ctx context.Context, id string) (Endpoint, error) {
	row, err := r.q.GetWebhookEndpointByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Endpoint{}, ErrNotFound
		}
		return Endpoint{}, err
	}
	return endpointFromRow(row), nil
}

func (r *pgRepository) InsertEndpoint(ctx context.Context, params InsertEndpointParams) (Endpoint, error) {
	row, err := r.q.InsertWebhookEndpoint(ctx, dbgen.InsertWebhookEndpointParams{
		ID:       params.ID,
		TenantID: params.TenantID,
		Url:      params.URL,
		Secret:   params.Secret,
	})
	if err != nil {
		return Endpoint{}, err
	}
	return endpointFromRow(row), nil
}

func (r *pgRepository) UpdateEndpointURL(ctx context.Context, id, url string) (Endpoint, error) {
	row, err := r.q.UpdateWebhookEndpointURL(ctx, dbgen.UpdateWebhookEndpointURLParams{
		ID:  id,
		Url: url,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Endpoint{}, ErrNotFound
		}
		return Endpoint{}, err
	}
	return endpointFromRow(row), nil
}

func (r *pgRepository) InsertDelivery(ctx context.Context, params InsertDeliveryParams) (Delivery, error) {
	row, err := r.q.InsertWebhookDelivery(ctx, dbgen.InsertWebhookDeliveryParams{
		ID:                params.ID,
		TenantID:          params.TenantID,
		WebhookEndpointID: params.WebhookEndpointID,
		EventType:         params.EventType,
		GenerationJobID:   params.GenerationJobID,
		Payload:           params.Payload,
	})
	if err != nil {
		return Delivery{}, err
	}
	return deliveryFromRow(row), nil
}

func (r *pgRepository) GetDeliveryByID(ctx context.Context, id string) (Delivery, error) {
	row, err := r.q.GetWebhookDeliveryByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Delivery{}, ErrNotFound
		}
		return Delivery{}, err
	}
	return deliveryFromRow(row), nil
}

func (r *pgRepository) MarkDeliveryResult(ctx context.Context, res DeliveryResult) error {
	var httpStatus *int32
	if res.HTTPStatus != 0 {
		s := int32(res.HTTPStatus)
		httpStatus = &s
	}
	var lastErr *string
	if res.Err != "" {
		e := res.Err
		lastErr = &e
	}
	return r.q.MarkWebhookDeliveryResult(ctx, dbgen.MarkWebhookDeliveryResultParams{
		ID:             res.DeliveryID,
		Status:         res.Status,
		LastHttpStatus: httpStatus,
		LastError:      lastErr,
	})
}

func endpointFromRow(row dbgen.WebhookEndpoint) Endpoint {
	return Endpoint{
		ID:       row.ID,
		TenantID: row.TenantID,
		URL:      row.Url,
		Secret:   row.Secret,
		IsActive: row.IsActive,
	}
}

func deliveryFromRow(row dbgen.WebhookDelivery) Delivery {
	return Delivery{
		ID:                row.ID,
		TenantID:          row.TenantID,
		WebhookEndpointID: row.WebhookEndpointID,
		EventType:         row.EventType,
		GenerationJobID:   row.GenerationJobID,
		Payload:           row.Payload,
		Status:            row.Status,
		AttemptCount:      row.AttemptCount,
	}
}
