// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apigen

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AdminProviderModelCircuitBreakerState.
const (
	Closed   AdminProviderModelCircuitBreakerState = "closed"
	HalfOpen AdminProviderModelCircuitBreakerState = "half_open"
	Open     AdminProviderModelCircuitBreakerState = "open"
)

// Defines values for AdminProviderModelStatus.
const (
	AdminProviderModelStatusActive   AdminProviderModelStatus = "active"
	AdminProviderModelStatusDegraded AdminProviderModelStatus = "degraded"
	AdminProviderModelStatusDisabled AdminProviderModelStatus = "disabled"
)

// Defines values for AdminRouteStatus.
const (
	AdminRouteStatusActive   AdminRouteStatus = "active"
	AdminRouteStatusDisabled AdminRouteStatus = "disabled"
)

// Defines values for AssetStatus.
const (
	AssetStatusArchived     AssetStatus = "archived"
	AssetStatusFailed       AssetStatus = "failed"
	AssetStatusPending      AssetStatus = "pending"
	AssetStatusPreviewReady AssetStatus = "preview_ready"
	AssetStatusReady        AssetStatus = "ready"
)

// Defines values for AssetType.
const (
	AssetTypeAngleVariant      AssetType = "angle_variant"
	AssetTypeArtifact          AssetType = "artifact"
	AssetTypeCharacterPortrait AssetType = "character_portrait"
	AssetTypeExpression        AssetType = "expression"
	AssetTypePlaceScene        AssetType = "place_scene"
)

// Defines values for BudgetPeriod.
const (
	Daily   BudgetPeriod = "daily"
	Monthly BudgetPeriod = "monthly"
)

// Defines values for BudgetScopeType.
const (
	Tenant BudgetScopeType = "tenant"
	Token  BudgetScopeType = "token"
	User   BudgetScopeType = "user"
	World  BudgetScopeType = "world"
)

// Defines values for BudgetStatus.
const (
	BudgetStatusActive   BudgetStatus = "active"
	BudgetStatusExceeded BudgetStatus = "exceeded"
	BudgetStatusPaused   BudgetStatus = "paused"
)

// Defines values for CostReservationStatus.
const (
	CostReservationStatusCommitted CostReservationStatus = "committed"
	CostReservationStatusFailed    CostReservationStatus = "failed"
	CostReservationStatusReleased  CostReservationStatus = "released"
	CostReservationStatusReserved  CostReservationStatus = "reserved"
)

// Defines values for FallbackPolicy.
const (
	AnyExisting    FallbackPolicy = "any_existing"
	CompatibleOnly FallbackPolicy = "compatible_only"
	None           FallbackPolicy = "none"
	PreviewAllowed FallbackPolicy = "preview_allowed"
)

// Defines values for GenerationJobAcceptedStatus.
const (
	GenerationJobAcceptedStatusQueued GenerationJobAcceptedStatus = "queued"
)

// Defines values for GenerationJobStatus.
const (
	GenerationJobStatusCancelled    GenerationJobStatus = "cancelled"
	GenerationJobStatusCompleted    GenerationJobStatus = "completed"
	GenerationJobStatusFailed       GenerationJobStatus = "failed"
	GenerationJobStatusPreviewReady GenerationJobStatus = "preview_ready"
	GenerationJobStatusQueued       GenerationJobStatus = "queued"
	GenerationJobStatusRunning      GenerationJobStatus = "running"
)

// Defines values for LatencyTier.
const (
	Balanced LatencyTier = "balanced"
	Fast     LatencyTier = "fast"
	Quality  LatencyTier = "quality"
)

// Defines values for MatchType.
const (
	CompatibleMatch   MatchType = "compatible_match"
	ExactMatch        MatchType = "exact_match"
	GeneratedRequired MatchType = "generated_required"
	PreviewFallback   MatchType = "preview_fallback"
)

// Defines values for OwnerType.
const (
	OwnerTypeArtifact  OwnerType = "artifact"
	OwnerTypeCharacter OwnerType = "character"
	OwnerTypePlace     OwnerType = "place"
)

// Defines values for PreviewCapability.
const (
	DerivedPreview PreviewCapability = "derived_preview"
	NoPreview      PreviewCapability = "no_preview"
	TruePreview    PreviewCapability = "true_preview"
)

// Defines values for PriceOperationType.
const (
	Edit         PriceOperationType = "edit"
	ImageToImage PriceOperationType = "image_to_image"
	TextToImage  PriceOperationType = "text_to_image"
	Upscale      PriceOperationType = "upscale"
	VariantPack  PriceOperationType = "variant_pack"
)

// Defines values for PriceUnitType.
const (
	Credit    PriceUnitType = "credit"
	Image     PriceUnitType = "image"
	Megapixel PriceUnitType = "megapixel"
	Request   PriceUnitType = "request"
	Second    PriceUnitType = "second"
)

// Defines values for ProviderCapability.
const (
	DraftOnly         ProviderCapability = "draft_only"
	IdentityCapable   ProviderCapability = "identity_capable"
	PackCapable       ProviderCapability = "pack_capable"
	ProductionCapable ProviderCapability = "production_capable"
	SceneCapable      ProviderCapability = "scene_capable"
)

// Defines values for ProviderModelStatus.
const (
	ProviderModelStatusActive   ProviderModelStatus = "active"
	ProviderModelStatusDegraded ProviderModelStatus = "degraded"
	ProviderModelStatusDisabled ProviderModelStatus = "disabled"
)

// Defines values for QualityTier.
const (
	Draft    QualityTier = "draft"
	High     QualityTier = "high"
	Standard QualityTier = "standard"
)

// Defines values for StyleMode.
const (
	CreatorStyle   StyleMode = "creator_style"
	OpenPrompt     StyleMode = "open_prompt"
	PresetStyle    StyleMode = "preset_style"
	ProviderNative StyleMode = "provider_native"
)

// Defines values for StyleProfileStatus.
const (
	StyleProfileStatusActive   StyleProfileStatus = "active"
	StyleProfileStatusArchived StyleProfileStatus = "archived"
)

// Defines values for VisualIdentityStatus.
const (
	VisualIdentityStatusActive   VisualIdentityStatus = "active"
	VisualIdentityStatusArchived VisualIdentityStatus = "archived"
)

// AdminProviderModel defines model for AdminProviderModel.
type AdminProviderModel struct {
	// Capabilities Capability tiers this model satisfies (used by the router).
	Capabilities []ProviderCapability `json:"capabilities"`

	// CircuitBreakerState Current circuit-breaker state. `open` means the router has
	// stopped routing new jobs to this provider after too many
	// recent failures.
	CircuitBreakerState *AdminProviderModelCircuitBreakerState `json:"circuit_breaker_state,omitempty"`
	DisabledAt          *time.Time                             `json:"disabled_at,omitempty"`
	DisabledByTokenId   *string                                `json:"disabled_by_token_id,omitempty"`

	// DisabledReason Reason text from the most recent admin disable action, if any.
	DisabledReason *string    `json:"disabled_reason,omitempty"`
	DisplayName    string     `json:"display_name"`
	Id             string     `json:"id"`
	LastFailureAt  *time.Time `json:"last_failure_at,omitempty"`

	// PreviewCapability Whether the provider model can return a fast low-cost preview
	// before the final asset. See ADR-010 and PRD 06 §3.4.
	// - `true_preview`: provider has a separate fast-preview path; the
	//   preview asset lands meaningfully before the final asset.
	// - `derived_preview`: provider only returns one image; the platform
	//   downscales it for thumbnail/preview tiers but generation latency
	//   is unchanged (no UX wait-time benefit).
	// - `no_preview`: no preview support; the API returns progress
	//   state (and a placeholder) until the final asset lands.
	PreviewCapability *PreviewCapability       `json:"preview_capability,omitempty"`
	ProviderId        string                   `json:"provider_id"`
	Status            AdminProviderModelStatus `json:"status"`
	SupportsHighRes   *bool                    `json:"supports_high_res,omitempty"`

	// SupportsPreview **Deprecated**, prefer `preview_capability`. Treat as
	// `preview_capability != no_preview`.
	SupportsPreview *bool `json:"supports_preview,omitempty"`
}

// AdminProviderModelCircuitBreakerState Current circuit-breaker state. `open` means the router has
// stopped routing new jobs to this provider after too many
// recent failures.
type AdminProviderModelCircuitBreakerState string

// AdminProviderModelStatus defines model for AdminProviderModel.Status.
type AdminProviderModelStatus string

// AdminReasonBody defines model for AdminReasonBody.
type AdminReasonBody struct {
	// Reason Human-readable reason for the admin action. Recorded on the
	// audit_event row. Required for every state-changing admin call.
	Reason string `json:"reason"`
}

// AdminRoute defines model for AdminRoute.
type AdminRoute struct {
	// AssetType Kind of visual asset.
	AssetType         AssetType  `json:"asset_type"`
	DisabledAt        *time.Time `json:"disabled_at,omitempty"`
	DisabledByTokenId *string    `json:"disabled_by_token_id,omitempty"`
	DisabledReason    *string    `json:"disabled_reason,omitempty"`
	Id                string     `json:"id"`

	// LatencyTier Latency preference for provider routing.
	LatencyTier LatencyTier `json:"latency_tier"`

	// Priority Routing priority within ties. Higher wins.
	Priority        *int   `json:"priority,omitempty"`
	ProviderModelId string `json:"provider_model_id"`

	// QualityTier Output quality tier requested for generation.
	QualityTier QualityTier      `json:"quality_tier"`
	Status      AdminRouteStatus `json:"status"`
}

// AdminRouteStatus defines model for AdminRoute.Status.
type AdminRouteStatus string

// AssetSearchRequest defines model for AssetSearchRequest.
type AssetSearchRequest struct {
	// AssetType Kind of visual asset.
	AssetType *AssetType `json:"asset_type,omitempty"`

	// FallbackPolicy Controls which retrieval outcomes count as a usable hit vs. forcing
	// generation. Default `compatible_only`. See
	// `docs/architecture/variant-compatibility-matrix.md` §5.
	FallbackPolicy *FallbackPolicy `json:"fallback_policy,omitempty"`
	OwnerId        *string         `json:"owner_id,omitempty"`

	// OwnerType Owning entity of a visual identity.
	OwnerType *OwnerType `json:"owner_type,omitempty"`

	// QualityTier Output quality tier requested for generation.
	QualityTier *QualityTier `json:"quality_tier,omitempty"`

	// StateVersion Requested state version for the entity. Defaults to current.
	// Set explicitly when requesting historical/flashback assets.
	StateVersion   *int    `json:"state_version,omitempty"`
	StyleProfileId *string `json:"style_profile_id,omitempty"`

	// StyleProfileVersion Requested style profile version. Optional; when set it must match
	// exactly for an `exact_match`. See
	// `docs/architecture/variant-compatibility-matrix.md` §4.
	StyleProfileVersion *int `json:"style_profile_version,omitempty"`

	// VariantFamily Filter / matrix-lookup family for the request. See
	// `docs/architecture/variant-compatibility-matrix.md` §6.
	VariantFamily    *string `json:"variant_family,omitempty"`
	VariantKey       *string `json:"variant_key,omitempty"`
	Version          *int    `json:"version,omitempty"`
	VisualIdentityId *string `json:"visual_identity_id,omitempty"`
	WorldId          *string `json:"world_id,omitempty"`
}

// AssetSearchResponse defines model for AssetSearchResponse.
type AssetSearchResponse struct {
	Assets []VisualAsset `json:"assets"`

	// CompatibilityScore 0.0–1.0 confidence that the returned asset is a safe substitution
	// for the requested variant. `1.0` for `exact_match`. Combines the
	// matrix rule's intrinsic confidence with the asset's `fallback_rank`.
	CompatibilityScore *float32 `json:"compatibility_score,omitempty"`

	// FallbackReason When `match_type` is `compatible_match` or `preview_fallback`,
	// the matrix rule that allowed the substitution (e.g.
	// `character.expression.warm→smiling.compatible`,
	// `place.time_of_day.day↔night.preview_only`). Useful for audit
	// and debugging.
	FallbackReason *string `json:"fallback_reason,omitempty"`

	// GenerationRecommended True when the client should follow up with a generate-pack
	// request (e.g. because only a compatible_match or
	// preview_fallback was returned, or `generated_required` was the
	// outcome).
	GenerationRecommended *bool `json:"generation_recommended,omitempty"`

	// MatchType How the retrieval layer resolved a request against stored assets,
	// per the variant compatibility matrix
	// (`docs/architecture/variant-compatibility-matrix.md` §3).
	MatchType *MatchType `json:"match_type,omitempty"`
}

// AssetStatus Lifecycle status of a stored visual asset.
type AssetStatus string

// AssetType Kind of visual asset.
type AssetType string

// BudgetPeriod Reset period for a cost budget.
type BudgetPeriod string

// BudgetScopeType Scope at which a cost budget applies. Budgets at narrower scopes
// (token, world, user) sit inside the parent tenant's budget; both
// must permit a reservation for it to succeed.
type BudgetScopeType string

// BudgetStatus Live status of a cost budget.
//   - active: enforcing normally.
//   - paused: enforcement disabled (e.g. for migration); reservations
//     still record but do not deny requests.
//   - exceeded: hard limit reached; new reservations rejected until
//     period reset or limit raised.
type BudgetStatus string

// CostBudget defines model for CostBudget.
type CostBudget struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Currency  string     `json:"currency"`
	Id        string     `json:"id"`

	// LimitAmount Hard cap in `currency` per `period`.
	LimitAmount string `json:"limit_amount"`

	// Period Reset period for a cost budget.
	Period BudgetPeriod `json:"period"`

	// ReservedAmount Sum of currently-held reservations for the current period
	// (status `reserved`). Read-only; computed by the platform.
	ReservedAmount *string `json:"reserved_amount,omitempty"`

	// ScopeId Identifier within the scope (e.g. `tenant_abc`, `tok_xyz`,
	// `world_42`, `user_7`). For `scope_type=tenant`, equal to
	// `tenant_id`.
	ScopeId string `json:"scope_id"`

	// ScopeType Scope at which a cost budget applies. Budgets at narrower scopes
	// (token, world, user) sit inside the parent tenant's budget; both
	// must permit a reservation for it to succeed.
	ScopeType BudgetScopeType `json:"scope_type"`

	// SpentAmount Sum of committed actuals for the current period (status
	// `committed`). Read-only; computed by the platform.
	SpentAmount *string `json:"spent_amount,omitempty"`

	// Status Live status of a cost budget.
	// - active: enforcing normally.
	// - paused: enforcement disabled (e.g. for migration); reservations
	//   still record but do not deny requests.
	// - exceeded: hard limit reached; new reservations rejected until
	//   period reset or limit raised.
	Status    BudgetStatus `json:"status"`
	TenantId  string       `json:"tenant_id"`
	UpdatedAt *time.Time   `json:"updated_at,omitempty"`
}

// CostBudgetMutable Fields editable on an existing budget.
type CostBudgetMutable struct {
	LimitAmount *string `json:"limit_amount,omitempty"`

	// Status Live status of a cost budget.
	// - active: enforcing normally.
	// - paused: enforcement disabled (e.g. for migration); reservations
	//   still record but do not deny requests.
	// - exceeded: hard limit reached; new reservations rejected until
	//   period reset or limit raised.
	Status *BudgetStatus `json:"status,omitempty"`
}

// CostBudgetWrite defines model for CostBudgetWrite.
type CostBudgetWrite struct {
	Currency    *string `json:"currency,omitempty"`
	LimitAmount string  `json:"limit_amount"`

	// Period Reset period for a cost budget.
	Period  BudgetPeriod `json:"period"`
	ScopeId string       `json:"scope_id"`

	// ScopeType Scope at which a cost budget applies. Budgets at narrower scopes
	// (token, world, user) sit inside the parent tenant's budget; both
	// must permit a reservation for it to succeed.
	ScopeType BudgetScopeType `json:"scope_type"`

	// Status Live status of a cost budget.
	// - active: enforcing normally.
	// - paused: enforcement disabled (e.g. for migration); reservations
	//   still record but do not deny requests.
	// - exceeded: hard limit reached; new reservations rejected until
	//   period reset or limit raised.
	Status *BudgetStatus `json:"status,omitempty"`

	// TenantId Required for non-tenant-scope budgets. For `scope_type=tenant`,
	// equal to `scope_id`.
	TenantId *string `json:"tenant_id,omitempty"`
}

// CostEvent defines model for CostEvent.
type CostEvent struct {
	ActualCostUsd    *string   `json:"actual_cost_usd,omitempty"`
	AssetId          *string   `json:"asset_id,omitempty"`
	CreatedAt        time.Time `json:"created_at"`
	DurationMs       *int      `json:"duration_ms,omitempty"`
	EstimatedCostUsd *string   `json:"estimated_cost_usd,omitempty"`
	Id               string    `json:"id"`
	JobId            *string   `json:"job_id,omitempty"`
	ModelId          *string   `json:"model_id,omitempty"`
	Operation        string    `json:"operation"`
	ProviderId       *string   `json:"provider_id,omitempty"`
	Status           string    `json:"status"`
	TokenId          *string   `json:"token_id,omitempty"`
}

// CostReservation defines model for CostReservation.
type CostReservation struct {
	// ActualAmount Committed cost from provider reporting. Null until the job
	// terminates and is reconciled.
	ActualAmount *string   `json:"actual_amount"`
	CreatedAt    time.Time `json:"created_at"`
	Currency     string    `json:"currency"`

	// EstimatedAmount Pre-flight cost estimate calculated from the price book.
	EstimatedAmount string `json:"estimated_amount"`

	// FailureReason Populated when `status = failed` (e.g. `budget_exceeded`,
	// `no_price_entry`).
	FailureReason   *string `json:"failure_reason,omitempty"`
	GenerationJobId string  `json:"generation_job_id"`
	Id              string  `json:"id"`

	// ReservedAmount Amount actually held against the budget. Normally equal to
	// `estimated_amount`; may exceed it slightly if the price book
	// includes a safety margin.
	ReservedAmount string `json:"reserved_amount"`

	// Status Lifecycle of a cost reservation. `reserved` is created pre-flight;
	// `committed` on job success with `actual_amount`; `released` on
	// job cancel/failure to return budget; `failed` if the reservation
	// itself could not be created (e.g. budget exceeded).
	Status    CostReservationStatus `json:"status"`
	TenantId  string                `json:"tenant_id"`
	UpdatedAt *time.Time            `json:"updated_at,omitempty"`
}

// CostReservationStatus Lifecycle of a cost reservation. `reserved` is created pre-flight;
// `committed` on job success with `actual_amount`; `released` on
// job cancel/failure to return budget; `failed` if the reservation
// itself could not be created (e.g. budget exceeded).
type CostReservationStatus string

// CreateStyleProfileRequest defines model for CreateStyleProfileRequest.
type CreateStyleProfileRequest struct {
	// DefaultQualityTier Output quality tier requested for generation.
	DefaultQualityTier *QualityTier `json:"default_quality_tier,omitempty"`
	Name               string       `json:"name"`
	NegativePrompt     *string      `json:"negative_prompt,omitempty"`
	PositivePrompt     string       `json:"positive_prompt"`

	// StyleMode How a style profile is sourced.
	StyleMode StyleMode `json:"style_mode"`
}

// CreateVisualIdentityRequest defines model for CreateVisualIdentityRequest.
type CreateVisualIdentityRequest struct {
	CanonicalVisualTraits map[string]interface{} `json:"canonical_visual_traits"`
	ConsistencyKey        *string                `json:"consistency_key,omitempty"`
	DisplayName           string                 `json:"display_name"`
	OwnerId               string                 `json:"owner_id"`

	// OwnerType Owning entity of a visual identity.
	OwnerType      OwnerType `json:"owner_type"`
	StyleProfileId string    `json:"style_profile_id"`
	WorldId        string    `json:"world_id"`
}

// Error Standard error body returned for all non-2xx responses. Served with
// content type `application/problem+json`. `code` is a stable, lowercase
// machine-readable identifier (e.g. `unauthorized`, `forbidden`,
// `internal_error`); `message` is human-readable; `request_id` matches
// the `X-Request-Id` response header.
type Error struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

// FallbackPolicy Controls which retrieval outcomes count as a usable hit vs. forcing
// generation. Default `compatible_only`. See
// `docs/architecture/variant-compatibility-matrix.md` §5.
type FallbackPolicy string

// GenerateArtifactRequest defines model for GenerateArtifactRequest.
type GenerateArtifactRequest struct {
	Description string `json:"description"`

	// FallbackPolicy Controls which retrieval outcomes count as a usable hit vs. forcing
	// generation. Default `compatible_only`. See
	// `docs/architecture/variant-compatibility-matrix.md` §5.
	FallbackPolicy *FallbackPolicy `json:"fallback_policy,omitempty"`

	// ForceRegenerate Phase 6A4 forced regeneration. When `true`, the artifact
	// exact-reuse lookup (Phase 6A2) is bypassed and the artifact is
	// always rendered fresh (reserve + enqueue + generate). The new
	// asset supersedes the prior ready asset of its exact slot
	// (tenant + world + style + quality + render hash): the predecessor
	// is archived and linked via `superseded_by_asset_id`, and the new
	// asset becomes the single ready row a later non-forced request
	// reuses, with `version` incremented. Default `false` is the
	// unchanged Phase 6A2 reuse behavior.
	ForceRegenerate *bool `json:"force_regenerate,omitempty"`

	// LatencyTier Latency preference for provider routing.
	LatencyTier *LatencyTier `json:"latency_tier,omitempty"`

	// QualityTier Output quality tier requested for generation.
	QualityTier    *QualityTier `json:"quality_tier,omitempty"`
	StyleProfileId string       `json:"style_profile_id"`
	WorldId        string       `json:"world_id"`
}

// GenerateCharacterPackRequest defines model for GenerateCharacterPackRequest.
type GenerateCharacterPackRequest struct {
	// FallbackPolicy Controls which retrieval outcomes count as a usable hit vs. forcing
	// generation. Default `compatible_only`. See
	// `docs/architecture/variant-compatibility-matrix.md` §5.
	FallbackPolicy *FallbackPolicy `json:"fallback_policy,omitempty"`

	// ForceRegenerate Phase 6A4 forced regeneration. When `true`, retrieval-before-
	// generation is bypassed for every required role: the whole pack is
	// priced and generated fresh (no reuse, no misses-only discount, no
	// all-hits synchronous completion). Each regenerated role's asset
	// supersedes the prior ready asset of its exact slot — the
	// predecessor is archived and linked via
	// `superseded_by_asset_id`, and the new asset becomes the single
	// ready row a later non-forced request reuses. Whole-pack only;
	// per-role regeneration is not supported. Default `false` is the
	// unchanged reuse-first behavior.
	ForceRegenerate *bool `json:"force_regenerate,omitempty"`

	// LatencyTier Latency preference for provider routing.
	LatencyTier *LatencyTier `json:"latency_tier,omitempty"`

	// PackTemplate Named pack template (PRD 04 §8.1) selecting a fixed set of
	// variant roles to generate:
	// `character_minimal_portrait_pack`, `character_expression_pack`,
	// `character_full_reference_pack`. Resolution precedence is
	// explicit `variant_keys` > `pack_template` > minimal default.
	// When `variant_keys` are supplied they win verbatim and the pack
	// is labelled `character_custom_pack`. An unknown template is
	// rejected with `400 invalid_request`.
	PackTemplate *string `json:"pack_template,omitempty"`

	// QualityTier Output quality tier requested for generation.
	QualityTier    *QualityTier `json:"quality_tier,omitempty"`
	StyleProfileId string       `json:"style_profile_id"`
	VariantKeys    *[]string    `json:"variant_keys,omitempty"`
	WorldId        string       `json:"world_id"`
}

// GeneratePlacePackRequest defines model for GeneratePlacePackRequest.
type GeneratePlacePackRequest struct {
	// FallbackPolicy Controls which retrieval outcomes count as a usable hit vs. forcing
	// generation. Default `compatible_only`. See
	// `docs/architecture/variant-compatibility-matrix.md` §5.
	FallbackPolicy *FallbackPolicy `json:"fallback_policy,omitempty"`

	// ForceRegenerate See GenerateCharacterPackRequest.force_regenerate.
	ForceRegenerate *bool `json:"force_regenerate,omitempty"`

	// LatencyTier Latency preference for provider routing.
	LatencyTier *LatencyTier `json:"latency_tier,omitempty"`

	// PackTemplate Named pack template (PRD 04 §8.2) selecting a fixed set of
	// variant roles to generate: `place_minimal_scene_pack`,
	// `place_time_of_day_pack`, `place_state_pack`. See
	// GenerateCharacterPackRequest.pack_template for precedence and
	// error semantics; the custom pack type is `place_custom_pack`.
	PackTemplate *string `json:"pack_template,omitempty"`

	// QualityTier Output quality tier requested for generation.
	QualityTier    *QualityTier `json:"quality_tier,omitempty"`
	StyleProfileId string       `json:"style_profile_id"`
	VariantKeys    *[]string    `json:"variant_keys,omitempty"`
	WorldId        string       `json:"world_id"`
}

// GenerationJob defines model for GenerationJob.
type GenerationJob struct {
	ActualCostUsd *string `json:"actual_cost_usd,omitempty"`

	// AssetPackId Set when this job created/extended an asset pack
	// (generate-pack endpoints). Pack progress is observed through
	// this job: `final_asset_ids` carries the per-item assets.
	AssetPackId     *string   `json:"asset_pack_id,omitempty"`
	CostEstimateUsd *string   `json:"cost_estimate_usd,omitempty"`
	CreatedAt       time.Time `json:"created_at"`
	ErrorCode       *string   `json:"error_code,omitempty"`
	ErrorMessage    *string   `json:"error_message,omitempty"`
	FinalAssetIds   *[]string `json:"final_asset_ids,omitempty"`
	Id              string    `json:"id"`
	JobType         string    `json:"job_type"`
	PreviewAssetIds *[]string `json:"preview_asset_ids,omitempty"`
	Retryable       *bool     `json:"retryable,omitempty"`

	// Status Lifecycle status of a generation job.
	Status           GenerationJobStatus `json:"status"`
	UpdatedAt        time.Time           `json:"updated_at"`
	VisualIdentityId *string             `json:"visual_identity_id,omitempty"`
}

// GenerationJobAccepted defines model for GenerationJobAccepted.
type GenerationJobAccepted struct {
	// AssetPackId ID of the `asset_pack` row created for this job. Returned only
	// by the two generate-pack endpoints (PRD 04 / ADR-008); absent
	// for single-asset jobs.
	AssetPackId *string `json:"asset_pack_id,omitempty"`

	// CostReservationId ID of the `cost_reservation` row created for this job. The
	// reservation is committed against the budget on job success and
	// released on failure/cancel.
	CostReservationId *string `json:"cost_reservation_id,omitempty"`
	Currency          *string `json:"currency,omitempty"`

	// EstimatedCostUsd Pre-flight cost estimate from the price book, in USD. Returned
	// when the route has at least one matching `provider_model_price`
	// entry. Null when the route allows an unpriced provider for
	// internal testing (`allow_unpriced_provider=true` per
	// `docs/architecture/cost-control.md`).
	EstimatedCostUsd *string                     `json:"estimated_cost_usd,omitempty"`
	JobId            string                      `json:"job_id"`
	Status           GenerationJobAcceptedStatus `json:"status"`
}

// GenerationJobAcceptedStatus defines model for GenerationJobAccepted.Status.
type GenerationJobAcceptedStatus string

// GenerationJobStatus Lifecycle status of a generation job.
type GenerationJobStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// JobAssetsResponse A generation job's delivered visual assets, in deterministic delivery
// order, each enriched with presigned per-tier download URLs (Phase 6B).
type JobAssetsResponse struct {
	Assets []VisualAsset `json:"assets"`
}

// LatencyTier Latency preference for provider routing.
type LatencyTier string

// MatchType How the retrieval layer resolved a request against stored assets,
// per the variant compatibility matrix
// (`docs/architecture/variant-compatibility-matrix.md` §3).
type MatchType string

// OwnerType Owning entity of a visual identity.
type OwnerType string

// PreviewCapability Whether the provider model can return a fast low-cost preview
// before the final asset. See ADR-010 and PRD 06 §3.4.
//   - `true_preview`: provider has a separate fast-preview path; the
//     preview asset lands meaningfully before the final asset.
//   - `derived_preview`: provider only returns one image; the platform
//     downscales it for thumbnail/preview tiers but generation latency
//     is unchanged (no UX wait-time benefit).
//   - `no_preview`: no preview support; the API returns progress
//     state (and a placeholder) until the final asset lands.
type PreviewCapability string

// PriceOperationType What kind of provider call a price entry covers.
type PriceOperationType string

// PriceUnitType Unit that `price_per_unit` is denominated in.
type PriceUnitType string

// ProviderCapability Capability tier of a provider model used by the router.
type ProviderCapability string

// ProviderModel defines model for ProviderModel.
type ProviderModel struct {
	// Capabilities Capability tiers this model satisfies (used by the router).
	Capabilities []ProviderCapability `json:"capabilities"`
	DisplayName  string               `json:"display_name"`
	Id           string               `json:"id"`

	// PreviewCapability Whether the provider model can return a fast low-cost preview
	// before the final asset. See ADR-010 and PRD 06 §3.4.
	// - `true_preview`: provider has a separate fast-preview path; the
	//   preview asset lands meaningfully before the final asset.
	// - `derived_preview`: provider only returns one image; the platform
	//   downscales it for thumbnail/preview tiers but generation latency
	//   is unchanged (no UX wait-time benefit).
	// - `no_preview`: no preview support; the API returns progress
	//   state (and a placeholder) until the final asset lands.
	PreviewCapability *PreviewCapability  `json:"preview_capability,omitempty"`
	ProviderId        string              `json:"provider_id"`
	Status            ProviderModelStatus `json:"status"`
	SupportsHighRes   *bool               `json:"supports_high_res,omitempty"`

	// SupportsPreview **Deprecated**, prefer `preview_capability`. Treat as
	// `preview_capability != no_preview`.
	SupportsPreview *bool `json:"supports_preview,omitempty"`
}

// ProviderModelStatus defines model for ProviderModel.Status.
type ProviderModelStatus string

// ProviderModelPrice defines model for ProviderModelPrice.
type ProviderModelPrice struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Currency ISO 4217 code.
	Currency      string    `json:"currency"`
	EffectiveFrom time.Time `json:"effective_from"`

	// EffectiveTo Null while the entry is the active price for its
	// (provider × model × operation_type). Set when superseded.
	EffectiveTo *time.Time `json:"effective_to"`
	Id          string     `json:"id"`

	// IsActive Convenience flag for "this is the currently quoted price."
	// Implementations must keep `is_active` synchronized with
	// `effective_from <= now < effective_to` (or `effective_to` null).
	IsActive bool    `json:"is_active"`
	ModelId  string  `json:"model_id"`
	Notes    *string `json:"notes,omitempty"`

	// OperationType What kind of provider call a price entry covers.
	OperationType PriceOperationType `json:"operation_type"`

	// PricePerUnit Fixed-decimal price in `currency` per `unit_type`. String to
	// preserve precision (e.g. "0.0140").
	PricePerUnit string `json:"price_per_unit"`
	ProviderId   string `json:"provider_id"`

	// Source Provenance of the price (e.g. `provider_pricing_page`,
	// `internal_benchmark`, `incident_review_2026_06_05`).
	Source *string `json:"source,omitempty"`

	// UnitType Unit that `price_per_unit` is denominated in.
	UnitType  PriceUnitType `json:"unit_type"`
	UpdatedAt *time.Time    `json:"updated_at,omitempty"`
}

// ProviderModelPriceMutable Fields editable on an existing price entry. To change
// `price_per_unit`, POST a new entry instead — the old one is
// retained for audit.
type ProviderModelPriceMutable struct {
	EffectiveTo *time.Time `json:"effective_to"`
	IsActive    *bool      `json:"is_active,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
}

// ProviderModelPriceWrite defines model for ProviderModelPriceWrite.
type ProviderModelPriceWrite struct {
	Currency      *string    `json:"currency,omitempty"`
	EffectiveFrom time.Time  `json:"effective_from"`
	EffectiveTo   *time.Time `json:"effective_to"`
	ModelId       string     `json:"model_id"`
	Notes         *string    `json:"notes,omitempty"`

	// OperationType What kind of provider call a price entry covers.
	OperationType PriceOperationType `json:"operation_type"`
	PricePerUnit  string             `json:"price_per_unit"`
	ProviderId    string             `json:"provider_id"`
	Source        *string            `json:"source,omitempty"`

	// UnitType Unit that `price_per_unit` is denominated in.
	UnitType PriceUnitType `json:"unit_type"`
}

// QualityTier Output quality tier requested for generation.
type QualityTier string

// StyleMode How a style profile is sourced.
type StyleMode string

// StylePreviewRequest Body for `POST /v1/styles/{style_id}/preview`. `world_id` is required
// because generated visual assets are world-scoped (Phase 6B).
type StylePreviewRequest struct {
	// QualityTier Output quality tier requested for generation.
	QualityTier *QualityTier `json:"quality_tier,omitempty"`
	WorldId     string       `json:"world_id"`
}

// StyleProfile defines model for StyleProfile.
type StyleProfile struct {
	// DefaultQualityTier Output quality tier requested for generation.
	DefaultQualityTier *QualityTier        `json:"default_quality_tier,omitempty"`
	Id                 string              `json:"id"`
	Name               string              `json:"name"`
	NegativePrompt     *string             `json:"negative_prompt,omitempty"`
	PositivePrompt     string              `json:"positive_prompt"`
	Status             *StyleProfileStatus `json:"status,omitempty"`

	// StyleMode How a style profile is sourced.
	StyleMode StyleMode `json:"style_mode"`
}

// StyleProfileStatus defines model for StyleProfile.Status.
type StyleProfileStatus string

// VisualAsset defines model for VisualAsset.
type VisualAsset struct {
	// AssetType Kind of visual asset.
	AssetType AssetType `json:"asset_type"`

	// CompatibilityTags Tags consulted by the variant compatibility matrix
	// (e.g. `generic_presence`, `preview_safe`,
	// `identity_anchor_eligible`).
	CompatibilityTags *[]string `json:"compatibility_tags,omitempty"`

	// FallbackAllowed Whether this asset may be returned as `preview_fallback` for
	// other variants. Default `false` for strong-emotion targets and
	// altered-state documents/artifacts.
	FallbackAllowed *bool `json:"fallback_allowed,omitempty"`

	// FallbackRank Lower = preferred fallback within its compatibility tier. Used
	// to pick the best candidate when several would qualify.
	FallbackRank *int `json:"fallback_rank,omitempty"`

	// FinalDownloadUrl Time-limited presigned `https` GET URL for the final/full-resolution
	// tier, the `high_res_url` object. Ephemeral; expires at
	// `url_expires_at`.
	FinalDownloadUrl *string `json:"final_download_url,omitempty"`
	HighResUrl       *string `json:"high_res_url,omitempty"`
	Id               string  `json:"id"`

	// IsIdentityAnchor True for anchor assets used as reference inputs. Anchor assets
	// must never be returned as a `compatible_match` for a non-anchor
	// display request — they are reference inputs, not display assets.
	IsIdentityAnchor *bool                   `json:"is_identity_anchor,omitempty"`
	LowResUrl        *string                 `json:"low_res_url,omitempty"`
	Metadata         *map[string]interface{} `json:"metadata,omitempty"`
	ModelId          *string                 `json:"model_id,omitempty"`

	// PreviewDownloadUrl Time-limited presigned `https` GET URL for the preview tier
	// (~768px short edge), the `low_res_url` object. Ephemeral; expires
	// at `url_expires_at`.
	PreviewDownloadUrl *string `json:"preview_download_url,omitempty"`
	PromptHash         *string `json:"prompt_hash,omitempty"`
	ProviderId         *string `json:"provider_id,omitempty"`
	Seed               *string `json:"seed,omitempty"`

	// StateVersion State version for the underlying entity at generation time
	// (independent of `visual_identity_version`, which is identity-level).
	// Used by the variant compatibility matrix to enforce strict
	// state boundaries (e.g. a destroyed-place asset is never a
	// fallback for an intact-place request).
	StateVersion *int `json:"state_version,omitempty"`

	// Status Lifecycle status of a stored visual asset.
	Status AssetStatus `json:"status"`

	// ThumbnailDownloadUrl Time-limited presigned `https` GET URL for the thumbnail tier
	// (~256px short edge). Minted at read time from the asset's
	// deterministic object key; expires at `url_expires_at`. Additive
	// in v0.6.0 (Phase 6B delivery). Present only when the read surface
	// is wired to object storage; the durable `s3://` provenance stays
	// on `thumbnail_url`.
	ThumbnailDownloadUrl *string `json:"thumbnail_download_url,omitempty"`
	ThumbnailUrl         *string `json:"thumbnail_url,omitempty"`

	// UrlExpiresAt Absolute expiry of the `*_download_url` fields. After this instant
	// the presigned URLs stop authenticating and a fresh read must be
	// issued. Set whenever the download URLs are present.
	UrlExpiresAt *time.Time `json:"url_expires_at,omitempty"`

	// VariantFamily Grouping used by the variant compatibility matrix
	// (e.g. `neutral`, `warm`, `strong_emotion`, `establishing`,
	// `document_clean`). See
	// `docs/architecture/variant-compatibility-matrix.md` §6.
	VariantFamily    *string `json:"variant_family,omitempty"`
	VariantKey       string  `json:"variant_key"`
	Version          int     `json:"version"`
	VisualIdentityId *string `json:"visual_identity_id,omitempty"`
	WorldId          *string `json:"world_id,omitempty"`
}

// VisualIdentity defines model for VisualIdentity.
type VisualIdentity struct {
	AnchorAssetIds        *[]string               `json:"anchor_asset_ids,omitempty"`
	CanonicalVisualTraits *map[string]interface{} `json:"canonical_visual_traits,omitempty"`
	ConsistencyKey        *string                 `json:"consistency_key,omitempty"`
	CurrentVersion        int                     `json:"current_version"`
	DisplayName           string                  `json:"display_name"`
	Id                    string                  `json:"id"`
	OwnerId               string                  `json:"owner_id"`

	// OwnerType Owning entity of a visual identity.
	OwnerType      OwnerType            `json:"owner_type"`
	Status         VisualIdentityStatus `json:"status"`
	StyleProfileId string               `json:"style_profile_id"`
	WorldId        string               `json:"world_id"`
}

// VisualIdentityStatus defines model for VisualIdentity.Status.
type VisualIdentityStatus string

// ArtifactId defines model for ArtifactId.
type ArtifactId = string

// AssetId defines model for AssetId.
type AssetId = string

// CharacterId defines model for CharacterId.
type CharacterId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// JobId defines model for JobId.
type JobId = string

// PlaceId defines model for PlaceId.
type PlaceId = string

// StyleId defines model for StyleId.
type StyleId = string

// WorldIdQuery defines model for WorldIdQuery.
type WorldIdQuery = string

// ErrorResponse Standard error body returned for all non-2xx responses. Served with
// content type `application/problem+json`. `code` is a stable, lowercase
// machine-readable identifier (e.g. `unauthorized`, `forbidden`,
// `internal_error`); `message` is human-readable; `request_id` matches
// the `X-Request-Id` response header.
type ErrorResponse = Error

// GetV1AdminCostBudgetsParams defines parameters for GetV1AdminCostBudgets.
type GetV1AdminCostBudgetsParams struct {
	TenantId  *string          `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`
	ScopeType *BudgetScopeType `form:"scope_type,omitempty" json:"scope_type,omitempty"`
	ScopeId   *string          `form:"scope_id,omitempty" json:"scope_id,omitempty"`
}

// GetV1AdminCostEventsParams defines parameters for GetV1AdminCostEvents.
type GetV1AdminCostEventsParams struct {
	TokenId       *string    `form:"token_id,omitempty" json:"token_id,omitempty"`
	ProviderId    *string    `form:"provider_id,omitempty" json:"provider_id,omitempty"`
	ModelId       *string    `form:"model_id,omitempty" json:"model_id,omitempty"`
	WorldId       *string    `form:"world_id,omitempty" json:"world_id,omitempty"`
	TenantId      *string    `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`
	CreatedAfter  *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`
	Limit         *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetV1AdminCostReservationsParams defines parameters for GetV1AdminCostReservations.
type GetV1AdminCostReservationsParams struct {
	TenantId      *string                `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`
	Status        *CostReservationStatus `form:"status,omitempty" json:"status,omitempty"`
	CreatedAfter  *time.Time             `form:"created_after,omitempty" json:"created_after,omitempty"`
	CreatedBefore *time.Time             `form:"created_before,omitempty" json:"created_before,omitempty"`
	Limit         *int                   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetV1AdminJobsParams defines parameters for GetV1AdminJobs.
type GetV1AdminJobsParams struct {
	Status        *GenerationJobStatus `form:"status,omitempty" json:"status,omitempty"`
	ProviderId    *string              `form:"provider_id,omitempty" json:"provider_id,omitempty"`
	WorldId       *string              `form:"world_id,omitempty" json:"world_id,omitempty"`
	TenantId      *string              `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`
	TokenId       *string              `form:"token_id,omitempty" json:"token_id,omitempty"`
	CreatedAfter  *time.Time           `form:"created_after,omitempty" json:"created_after,omitempty"`
	CreatedBefore *time.Time           `form:"created_before,omitempty" json:"created_before,omitempty"`
	ErrorCode     *string              `form:"error_code,omitempty" json:"error_code,omitempty"`
	Limit         *int                 `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostV1AdminJobsJobIdRetryJSONBody defines parameters for PostV1AdminJobsJobIdRetry.
type PostV1AdminJobsJobIdRetryJSONBody struct {
	// Force Override the retryable check.
	Force  *bool  `json:"force,omitempty"`
	Reason string `json:"reason"`
}

// GetV1AdminPriceBookParams defines parameters for GetV1AdminPriceBook.
type GetV1AdminPriceBookParams struct {
	ProviderId    *string             `form:"provider_id,omitempty" json:"provider_id,omitempty"`
	ModelId       *string             `form:"model_id,omitempty" json:"model_id,omitempty"`
	OperationType *PriceOperationType `form:"operation_type,omitempty" json:"operation_type,omitempty"`
	OnlyActive    *bool               `form:"only_active,omitempty" json:"only_active,omitempty"`
}

// PostV1ArtifactsArtifactIdGenerateParams defines parameters for PostV1ArtifactsArtifactIdGenerate.
type PostV1ArtifactsArtifactIdGenerateParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1AssetsAssetIdRegenerateParams defines parameters for PostV1AssetsAssetIdRegenerate.
type PostV1AssetsAssetIdRegenerateParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1CharactersCharacterIdGeneratePackParams defines parameters for PostV1CharactersCharacterIdGeneratePack.
type PostV1CharactersCharacterIdGeneratePackParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetV1CharactersCharacterIdVisualIdentityParams defines parameters for GetV1CharactersCharacterIdVisualIdentity.
type GetV1CharactersCharacterIdVisualIdentityParams struct {
	// WorldId World ID used to scope the owner lookup. Visual identities are unique
	// by tenant_id + world_id + owner_type + owner_id.
	WorldId WorldIdQuery `form:"world_id" json:"world_id"`
}

// PostV1CharactersCharacterIdVisualIdentityParams defines parameters for PostV1CharactersCharacterIdVisualIdentity.
type PostV1CharactersCharacterIdVisualIdentityParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1PlacesPlaceIdGeneratePackParams defines parameters for PostV1PlacesPlaceIdGeneratePack.
type PostV1PlacesPlaceIdGeneratePackParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetV1PlacesPlaceIdVisualIdentityParams defines parameters for GetV1PlacesPlaceIdVisualIdentity.
type GetV1PlacesPlaceIdVisualIdentityParams struct {
	// WorldId World ID used to scope the owner lookup. Visual identities are unique
	// by tenant_id + world_id + owner_type + owner_id.
	WorldId WorldIdQuery `form:"world_id" json:"world_id"`
}

// PostV1PlacesPlaceIdVisualIdentityParams defines parameters for PostV1PlacesPlaceIdVisualIdentity.
type PostV1PlacesPlaceIdVisualIdentityParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1StylesStyleIdPreviewParams defines parameters for PostV1StylesStyleIdPreview.
type PostV1StylesStyleIdPreviewParams struct {
	// IdempotencyKey Client-generated idempotency key. The same key + token + endpoint + body
	// hash returns the same job. Same key + different body returns 409.
	// See `idempotency.md`.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1AdminCostBudgetsJSONRequestBody defines body for PostV1AdminCostBudgets for application/json ContentType.
type PostV1AdminCostBudgetsJSONRequestBody = CostBudgetWrite

// PutV1AdminCostBudgetsBudgetIdJSONRequestBody defines body for PutV1AdminCostBudgetsBudgetId for application/json ContentType.
type PutV1AdminCostBudgetsBudgetIdJSONRequestBody = CostBudgetMutable

// PostV1AdminJobsJobIdCancelJSONRequestBody defines body for PostV1AdminJobsJobIdCancel for application/json ContentType.
type PostV1AdminJobsJobIdCancelJSONRequestBody = AdminReasonBody

// PostV1AdminJobsJobIdRetryJSONRequestBody defines body for PostV1AdminJobsJobIdRetry for application/json ContentType.
type PostV1AdminJobsJobIdRetryJSONRequestBody PostV1AdminJobsJobIdRetryJSONBody

// PostV1AdminPriceBookJSONRequestBody defines body for PostV1AdminPriceBook for application/json ContentType.
type PostV1AdminPriceBookJSONRequestBody = ProviderModelPriceWrite

// PutV1AdminPriceBookPriceIdJSONRequestBody defines body for PutV1AdminPriceBookPriceId for application/json ContentType.
type PutV1AdminPriceBookPriceIdJSONRequestBody = ProviderModelPriceMutable

// PostV1AdminProvidersProviderIdDisableJSONRequestBody defines body for PostV1AdminProvidersProviderIdDisable for application/json ContentType.
type PostV1AdminProvidersProviderIdDisableJSONRequestBody = AdminReasonBody

// PostV1AdminProvidersProviderIdEnableJSONRequestBody defines body for PostV1AdminProvidersProviderIdEnable for application/json ContentType.
type PostV1AdminProvidersProviderIdEnableJSONRequestBody = AdminReasonBody

// PostV1AdminRoutesRouteIdDisableJSONRequestBody defines body for PostV1AdminRoutesRouteIdDisable for application/json ContentType.
type PostV1AdminRoutesRouteIdDisableJSONRequestBody = AdminReasonBody

// PostV1AdminRoutesRouteIdEnableJSONRequestBody defines body for PostV1AdminRoutesRouteIdEnable for application/json ContentType.
type PostV1AdminRoutesRouteIdEnableJSONRequestBody = AdminReasonBody

// PostV1ArtifactsArtifactIdGenerateJSONRequestBody defines body for PostV1ArtifactsArtifactIdGenerate for application/json ContentType.
type PostV1ArtifactsArtifactIdGenerateJSONRequestBody = GenerateArtifactRequest

// PostV1AssetsSearchJSONRequestBody defines body for PostV1AssetsSearch for application/json ContentType.
type PostV1AssetsSearchJSONRequestBody = AssetSearchRequest

// PostV1CharactersCharacterIdGeneratePackJSONRequestBody defines body for PostV1CharactersCharacterIdGeneratePack for application/json ContentType.
type PostV1CharactersCharacterIdGeneratePackJSONRequestBody = GenerateCharacterPackRequest

// PostV1CharactersCharacterIdVisualIdentityJSONRequestBody defines body for PostV1CharactersCharacterIdVisualIdentity for application/json ContentType.
type PostV1CharactersCharacterIdVisualIdentityJSONRequestBody = CreateVisualIdentityRequest

// PostV1PlacesPlaceIdGeneratePackJSONRequestBody defines body for PostV1PlacesPlaceIdGeneratePack for application/json ContentType.
type PostV1PlacesPlaceIdGeneratePackJSONRequestBody = GeneratePlacePackRequest

// PostV1PlacesPlaceIdVisualIdentityJSONRequestBody defines body for PostV1PlacesPlaceIdVisualIdentity for application/json ContentType.
type PostV1PlacesPlaceIdVisualIdentityJSONRequestBody = CreateVisualIdentityRequest

// PostV1StylesJSONRequestBody defines body for PostV1Styles for application/json ContentType.
type PostV1StylesJSONRequestBody = CreateStyleProfileRequest

// PostV1StylesStyleIdPreviewJSONRequestBody defines body for PostV1StylesStyleIdPreview for application/json ContentType.
type PostV1StylesStyleIdPreviewJSONRequestBody = StylePreviewRequest
